export default class ListeMotsProposables {
	// Ordre dans lequel les mots sont choisis jour après jour. 
	public static readonly DictionnaireFR: Map<string, number> = new Map<string, number>([
		["BALBUTO", 3],
		["NOSTENFER", 2],
		["OYACATA", 9],
		["RAMBOUM", 3],
		["ROUCARNAGE", 1],
		["INSOLOURDO", 2],
		["TAUPIQUEUR", 1],
		["PALARTICHO", 8],
		["AQUALI", 1],
		["MEGAPAGOS", 5],
		["BAGGAID", 5],
		["VACILYS", 3],
		["PANDARBARE", 6],
		["BOGUERISSE", 6],
		["PANDESPIEGLE", 6],
		["LUGIA", 2],
		["MENTALI", 2],
		["COLOSSINGE", 1],
		["BABIMANTA", 4],
		["MESMERELLA", 5],
		["PONCHIOT", 5],
		["MIMITOSS", 1],
		["TROPIUS", 3],
		["BULBIZARRE", 1],
		["KARACLEE", 5],
		["POMDOROCHI", 9],
		["PICHU", 2],
		["CRYODO", 9],
		["TOGETIC", 2],
		["MAGEARNA", 7],
		["FULGULAIRO", 9],
		["TERRAISTE", 9],
		["MIGALOS", 2],
		["PACHYRADJAH", 8],
		["VOSTOURNO", 5],
		["BOUSTIFLOR", 1],
		["MACRONIUM", 2],
		["REGIELEKI", 8],
		["AKWAKWAK", 1],
		["MIRAIDON", 9],
		["FORGELLA", 9],
		["MANZAI", 4],
		["CROCOGRIL", 9],
		["ENGLOUTYRAN", 7],
		["YANMEGA", 4],
		["PATACHIOT", 9],
		["MINOTAUPE", 5],
		["CRABOMINABLE", 7],
		["PITROUILLE", 6],
		["SPOINK", 3],
		["ZARUDE", 8],
		["PAUME-DE-FER", 9],
		["BALIGNON", 3],
		["TADMORV", 1],
		["LARVEYETTE", 5],
		["CHAPOTUS", 8],
		["MELODELFE", 1],
		["COATOX", 4],
		["GIGANSEL", 9],
		["BRUYVERNE", 6],
		["FLABEBE", 6],
		["TENGALICE", 3],
		["MOUMOUTON", 8],
		["NIDOKING", 1],
		["FARIGIRAF", 9],
		["OTARLETTE", 7],
		["KANGOUREX", 1],
		["POLTCHAGEIST", 9],
		["CERIBOU", 4],
		["SABELETTE", 1],
		["SCALPROIE", 5],
		["MANGRIFF", 3],
		["PONDRALUGON", 9],
		["TROUSSELIN", 6],
		["DIMORET", 4],
		["GRIBOURAIGNE", 9],
		["MOMARTIK", 4],
		["KRABBY", 1],
		["PORYGON2", 2],
		["SEPIATROCE", 6],
		["MACHOC", 1],
		["PALMAVAL", 9],
		["HASTACUDA", 8],
		["TRIOPIKEAU", 9],
		["KICKLEE", 1],
		["TOKOTORO", 7],
		["EFFLECHE", 7],
		["ROSABYSS", 3],
		["COLOMBEAU", 5],
		["FLORECLAT", 9],
		["GOLGOPATHE", 6],
		["MAMANBO", 5],
		["CARMADURA", 9],
		["METAMORPH", 1],
		["ROSERADE", 4],
		["MAGBY", 2],
		["EPINE-DE-FER", 9],
		["ESCROCO", 5],
		["ZIGZATON", 3],
		["DIALGA", 4],
		["QULBUTOKE", 2],
		["METANG", 3],
		["VIRIDIUM", 5],
		["ALAKAZAM", 1],
		["ESCARGAUME", 5],
		["POMDEPIK", 2],
		["PONCHIEN", 5],
		["METENO", 7],
		["NIGOSIER", 8],
		["QUARTERMAC", 7],
		["AMA-AMA", 7],
		["BAUDRIVE", 4],
		["MOUMOUFLON", 8],
		["ENTEI", 2],
		["LAMPEROIE", 5],
		["SOLOCHI", 5],
		["SIMIABRAZ", 4],
		["VIBRANINF", 3],
		["MATOURGEON", 9],
		["COUDLANGUE", 4],
		["SKELENOX", 3],
		["EVOLI", 1],
		["KECLEON", 3],
		["ROUBLENARD", 8],
		["HELIATRONC", 2],
		["NENUPIOT", 3],
		["CORVAILLUS", 8],
		["DESSELIANDE", 6],
		["MIAMIASME", 5],
		["ROC-DE-FER", 9],
		["CHENISELLE", 4],
		["IRE-FOUDRE", 9],
		["MUPLODOCUS", 6],
		["FEUNNEC", 6],
		["ECTOPLASMA", 1],
		["NOSFERAPTI", 1],
		["DEBUGANT", 2],
		["KATAGAMI", 7],
		["BOUMATA", 7],
		["CARCHACROK", 4],
		["VICTINI", 5],
		["DOLMAN", 8],
		["REMORAID", 2],
		["SOPORIFIK", 1],
		["FLAMENROULE", 9],
		["MARACACHI", 5],
		["CHENITI", 4],
		["POHMOTTE", 9],
		["MIMANTIS", 7],
		["BLEUSEILLE", 8],
		["DARUMAROND", 5],
		["MACHOPEUR", 1],
		["BOULDENEU", 4],
		["CHETIFLOR", 1],
		["GOUROUTAN", 7],
		["DEOXYS", 3],
		["SYLVEROY", 8],
		["ECRAPINCE", 3],
		["BETOCHEF", 5],
		["DOGRINO", 9],
		["CRUSTABRI", 1],
		["GRINGOLEM", 5],
		["PRINPLOUF", 4],
		["PIJAKO", 4],
		["VROMBI", 9],
		["AXOLOTO", 2],
		["TOKORICO", 7],
		["FLORGES", 6],
		["GARDEVOIR", 3],
		["MEGANIUM", 2],
		["AZURILL", 3],
		["SERPANG", 3],
		["CHARPENTI", 5],
		["NIDORAN♀", 1],
		["PTYRANIDUR", 6],
		["TOGEDEMARU", 7],
		["REGIDRAGO", 8],
		["NOACIER", 5],
		["AEROPTERYX", 5],
		["MONORPALE", 6],
		["ARKEAPTI", 5],
		["WAILORD", 3],
		["SHIFOURS", 8],
		["OBALIE", 3],
		["GALVARAN", 6],
		["PLUMELINE", 7],
		["RESHIRAM", 5],
		["MIMIGAL", 2],
		["COLHOMARD", 3],
		["SCORVOL", 4],
		["CHARBAMBIN", 9],
		["SELUTIN", 9],
		["LOVDISC", 3],
		["VOLCANION", 6],
		["GIVRALI", 4],
		["KRANIDOS", 4],
		["EOKO", 3],
		["SOVKIPOU", 7],
		["SILVALLIE", 7],
		["MASCAIMAN", 5],
		["EMBRYLEX", 2],
		["ZEBLITZ", 5],
		["OCTILLERY", 2],
		["CASTORNO", 4],
		["CRAPAROI", 9],
		["ASPICOT", 1],
		["BARGANTUA", 5],
		["OSSELAIT", 1],
		["PERSIAN", 1],
		["ALIGATUEUR", 2],
		["MIASCARADE", 9],
		["DEDENNE", 6],
		["GRENOUSSE", 6],
		["CARATROC", 2],
		["GROUDON", 3],
		["RONGOURMAND", 8],
		["NIDORINA", 1],
		["PTERA", 1],
		["CORNEBRE", 2],
		["FOURBELIN", 8],
		["SYMBIOS", 5],
		["LUDICOLO", 3],
		["CONCOMBAFFE", 7],
		["ARTIKODIN", 1],
		["REGIGIGAS", 4],
		["TARINORME", 4],
		["ABSOL", 3],
		["BRUTAPODE", 5],
		["TOKOPISCO", 7],
		["ARMULYS", 3],
		["BACABOUH", 7],
		["FAVIANOS", 9],
		["EMOLGA", 5],
		["TETES-DE-FER", 9],
		["GERMIGNON", 2],
		["AIRMURE", 2],
		["LAPOREILLE", 4],
		["GOLEMASTOC", 5],
		["GRILLEPATTES", 8],
		["COSMOG", 7],
		["COUANETON", 5],
		["ROCABOT", 7],
		["MAMMOCHON", 4],
		["VOLTALI", 1],
		["GRANBULL", 2],
		["DOUDOUVET", 5],
		["HYDRAGLA", 8],
		["KADABRA", 1],
		["ROZBOUTON", 4],
		["BLIZZI", 4],
		["METALOSSE", 3],
		["ONIX", 1],
		["GRINDUR", 5],
		["PIERROTEKNIK", 7],
		["CRIKZIK", 4],
		["BLANCOTON", 8],
		["KOKIYAS", 1],
		["WAILMER", 3],
		["SKITTY", 3],
		["GEOLITHE", 5],
		["MARISSON", 6],
		["CHAFFREUX", 4],
		["FEUILOUTAN", 5],
		["BELDENEIGE", 8],
		["CRABICOQUE", 5],
		["KORILLON", 4],
		["SOLGALEO", 7],
		["GRAINIPIOT", 3],
		["DRAIEUL", 7],
		["LOMBRE", 3],
		["DRASCORE", 4],
		["SCOLOCENDRE", 8],
		["EMPIFLOR", 1],
		["FLAMBINO", 8],
		["FLAMAJOU", 5],
		["MYSTHERBE", 1],
		["FEROSINGE", 1],
		["BANSHITROUYE", 6],
		["GARDE-DE-FER", 9],
		["LOKHLASS", 1],
		["ARCANIN", 1],
		["FLOBIO", 3],
		["LAGGRON", 3],
		["ASTRONELLE", 8],
		["ZERAORA", 7],
		["NINJASK", 3],
		["GUERIAIGLE", 5],
		["YUYU", 9],
		["LIMAGMA", 2],
		["GIRAFARIG", 2],
		["SORCILENCE", 8],
		["PHOGLEUR", 3],
		["RONFLEX", 1],
		["COURROUSINGE", 9],
		["LIBEGON", 3],
		["FRISON", 5],
		["TAG-TAG", 9],
		["NUCLEOS", 5],
		["GAMBLAST", 6],
		["POMDRAPI", 8],
		["FARFUREX", 8],
		["PTIRAVI", 4],
		["ELEKABLE", 4],
		["BALBALEZE", 9],
		["HARIYAMA", 3],
		["CREHELF", 4],
		["BRINDIBOU", 7],
		["MUNNA", 5],
		["CREFADET", 4],
		["PONYTA", 1],
		["POICHIGEON", 5],
		["RAPION", 4],
		["LAMPIGNON", 7],
		["DRATATIN", 8],
		["CLAMIRAL", 5],
		["LUCARIO", 4],
		["FULGUDOG", 8],
		["CREMY", 8],
		["PYROLI", 1],
		["COUAFAREL", 6],
		["MOTORIZARD", 9],
		["CRAPUSTULE", 5],
		["TEDDIURSA", 2],
		["INCISACHE", 5],
		["PECHAMINUS", 9],
		["SEPIATOP", 6],
		["PYRONILLE", 5],
		["POMDRAMOUR", 9],
		["VISKUSE", 5],
		["TARENBULLE", 7],
		["RATTATA", 1],
		["DEMOLOSSE", 2],
		["YMPHECT", 2],
		["ARBOK", 1],
		["ELECSPRINT", 3],
		["STEELIX", 2],
		["SORBOUL", 5],
		["FOUINETTE", 2],
		["BASTIODON", 4],
		["MOUFOUETTE", 4],
		["TENEFIX", 3],
		["SERACRAWL", 6],
		["TERACLOPE", 3],
		["TORGAMORD", 8],
		["WATTAPIK", 8],
		["SCORPLANE", 2],
		["CRABARAQUE", 5],
		["CORBOSS", 4],
		["LIPPOUTI", 2],
		["PICLAIRON", 7],
		["SONISTRELLE", 6],
		["MARAISTE", 2],
		["APITRINI", 4],
		["PRISMILLON", 6],
		["TRITOSOR", 4],
		["CLEOPSYTRA", 9],
		["TORTANK", 1],
		["POHM", 9],
		["VIROVENT", 9],
		["CANINOS", 1],
		["FLOTAJOU", 5],
		["PELAGE-SABLE", 9],
		["COLIMUCUS", 6],
		["SELEROC", 3],
		["PASHMILLA", 5],
		["NANMEOUIE", 5],
		["LOUGAROC", 7],
		["JUNGKO", 3],
		["CORAYON", 2],
		["SUPERDOFIN", 9],
		["KORAIDON", 9],
		["BATRACNE", 5],
		["JOLIFLOR", 2],
		["FEUNARD", 1],
		["MAJASPIC", 5],
		["NOSFERALTO", 1],
		["HELEDELLE", 3],
		["TRANCHODON", 5],
		["SINISTRAIL", 7],
		["CHARKOS", 4],
		["SAPEREAU", 6],
		["GOUPILOU", 8],
		["COCOTINE", 6],
		["NECROZMA", 7],
		["VOLTORBE", 1],
		["GOELISE", 3],
		["CARAPUCE", 1],
		["FORGELINA", 9],
		["SALAMECHE", 1],
		["SOLAROC", 3],
		["THEFFROI", 8],
		["LANTURN", 2],
		["STRASSIE", 6],
		["LAMANTINE", 1],
		["MARCACRIN", 2],
		["HIPPODOCUS", 4],
		["TOUDOUDOU", 2],
		["RHINOLOVE", 5],
		["CHARIBARI", 8],
		["MIASMAX", 5],
		["IGUOLTA", 6],
		["GROMAGO", 9],
		["MALAMANDRE", 7],
		["LIXY", 4],
		["KEUNOTOR", 4],
		["FEUILLAJOU", 5],
		["SABLAIREAU", 1],
		["MIMIQUI", 7],
		["CHRYSACIER", 1],
		["MELOETTA", 5],
		["PAPINOX", 3],
		["RATTATAC", 1],
		["EXCAVARENNE", 6],
		["DARDARGNAN", 1],
		["FLAMBUSARD", 6],
		["FLINGOUSTE", 6],
		["LEOPARDUS", 5],
		["HOOPA", 6],
		["STATITIK", 5],
		["RIOLU", 4],
		["ARAKDO", 3],
		["BOSKARA", 4],
		["KRABBOSS", 1],
		["TOGEPI", 2],
		["SHARPEDO", 3],
		["PYRAX", 5],
		["GRODOUDOU", 1],
		["LARMELEON", 8],
		["AVALTOUT", 3],
		["CACNEA", 3],
		["CRESSELIA", 4],
		["LEZARGUS", 8],
		["REXILLIUS", 6],
		["CHUCHMUR", 3],
		["OPERMINE", 6],
		["MAKUHITA", 3],
		["TRIOPIKEUR", 1],
		["KELDEO", 5],
		["TUTANKAFER", 5],
		["CROCORIBLE", 5],
		["ELECTHOR", 1],
		["FARFADUVET", 5],
		["ANORITH", 3],
		["EXAGIDE", 6],
		["BOURRINOS", 7],
		["GAMBEX", 9],
		["MITE-DE-FER", 9],
		["COTOVOL", 2],
		["GENESECT", 5],
		["SUCROQUIN", 6],
		["MALOSSE", 2],
		["SCALPEREUR", 9],
		["SUICUNE", 2],
		["AMPIBIDOU", 9],
		["KHELOCROK", 8],
		["SERPENTE-EAU", 9],
		["ZOROARK", 5],
		["VORASTERIE", 7],
		["LARVADAR", 8],
		["CHRYSAPILE", 7],
		["NOCTUNOIR", 4],
		["GOUPELIN", 6],
		["RATENTIF", 5],
		["ETOURMI", 4],
		["TYPHLOSION", 2],
		["ARCEUS", 4],
		["MUSTEBOUEE", 4],
		["RONGRIGOU", 8],
		["MAGNETI", 1],
		["SPECTRUM", 1],
		["HIPPOPOTAS", 4],
		["CUPCANAILLE", 6],
		["FRIGODO", 9],
		["NIDORAN♂", 1],
		["PACHIRISU", 4],
		["ZEBIBRON", 5],
		["OTAQUIN", 7],
		["LAPYRO", 8],
		["WAGOMINE", 8],
		["NOCTALI", 2],
		["LUXRAY", 4],
		["LESTOMBAILE", 9],
		["MAGANON", 4],
		["VIREVORREUR", 9],
		["TOURNICOTON", 8],
		["FORETRESS", 2],
		["AMONISTAR", 1],
		["VAUTUTRICE", 5],
		["RHINASTOC", 4],
		["BRASEGALI", 3],
		["COXY", 2],
		["LARVIBULE", 7],
		["ANGOLIATH", 8],
		["DODUO", 1],
		["TORTIPOUSS", 4],
		["GALEGON", 3],
		["AMAGARA", 6],
		["POUSSIFEU", 3],
		["BRUTALIBRE", 6],
		["TERHAL", 3],
		["BERASCA", 9],
		["TORTERRA", 4],
		["COSMOVUM", 7],
		["GRANIVOL", 2],
		["DONPHAN", 2],
		["PIETACE", 9],
		["ANCHWATT", 5],
		["DARUMACHO", 5],
		["ARCKO", 3],
		["GALVAGON", 8],
		["DRAGMARA", 6],
		["STAROSS", 1],
		["FEUFOREVE", 2],
		["QWILPIK", 8],
		["RAMPE-AILES", 9],
		["RAYQUAZA", 3],
		["REPTINCEL", 1],
		["GRIMALIN", 8],
		["MYGAVOLT", 5],
		["NOUNOURSON", 7],
		["CABLIFERE", 7],
		["SIDERELLA", 5],
		["AMONITA", 1],
		["SMOGO", 1],
		["CARVANHA", 3],
		["COCONFORT", 1],
		["HYPOROI", 2],
		["DRATTAK", 3],
		["HACHECATEUR", 8],
		["KAIMINUS", 2],
		["BRIOCHIEN", 9],
		["MOUFFLAIR", 4],
		["GRAHYENA", 3],
		["FLAMIAOU", 7],
		["CLIC", 5],
		["MATOUFEU", 7],
		["MELO", 2],
		["NATU", 2],
		["ORATORIA", 7],
		["STALGAMIN", 3],
		["TERRACRUEL", 9],
		["CHARTOR", 3],
		["MASSKO", 3],
		["ZARBI", 2],
		["CHARMILLON", 3],
		["TAUPIKEAU", 9],
		["BIBICHUT", 8],
		["ARMALDO", 3],
		["HOOTHOOT", 2],
		["OGERPON", 9],
		["CELEBI", 2],
		["LILLITERELLE", 9],
		["CANARBELLO", 9],
		["HO-OH", 2],
		["COQUIPERL", 3],
		["HERICENDRE", 2],
		["TYGNON", 1],
		["KABUTOPS", 1],
		["BRANETTE", 3],
		["FROUSSARDINE", 7],
		["RHINOCORNE", 1],
		["DINOCLIER", 4],
		["TETARTE", 1],
		["MORDUDOR", 9],
		["GROTADMORV", 1],
		["BEKAGLACON", 8],
		["ARCHEDUC", 7],
		["FLAGADOSS", 1],
		["FUNECIRE", 5],
		["FILENTRAPPE", 9],
		["NODULITHE", 5],
		["DEFLAISAN", 5],
		["LAKMECYGNE", 5],
		["BLINDEPIQUE", 6],
		["CHACRIPAN", 5],
		["OSSATUEUR", 1],
		["LEVEINARD", 1],
		["DEMETEROS", 5],
		["VORTENTE", 4],
		["MARILL", 2],
		["ONIGLALI", 3],
		["LINEON", 3],
		["ARCHEOMIRE", 4],
		["LEPIDONILLE", 6],
		["GRUIKUI", 5],
		["HYPOCEAN", 1],
		["GUERILANDE", 7],
		["PICASSAUT", 7],
		["FONGUS-FURIE", 9],
		["PTITARD", 1],
		["DENTICRISSE", 7],
		["MUCIOLE", 3],
		["CARABAFFE", 1],
		["DIAMAT", 5],
		["FERMITE", 5],
		["CERIFLOR", 4],
		["CREFOLLET", 4],
		["MELTAN", 7],
		["AEROMITE", 1],
		["CRYPTERO", 5],
		["FLOETTE", 6],
		["MAGIREVE", 4],
		["PIAFABEC", 1],
		["TOKOPIYON", 7],
		["CHARMILLY", 8],
		["SORBEBE", 5],
		["LATIAS", 3],
		["STARI", 1],
		["TREPASSABLE", 7],
		["OUISTICRAM", 4],
		["REGIROCK", 3],
		["CACTURNE", 3],
		["XERNEAS", 6],
		["GLAIVODO", 9],
		["KRAKNOIX", 3],
		["COUPENOTTE", 5],
		["LUNALA", 7],
		["FRISSONILLE", 8],
		["MINIDRACO", 1],
		["FLORIZARRE", 1],
		["ECAYON", 4],
		["INSECATEUR", 1],
		["YVELTAL", 6],
		["EKAISER", 7],
		["CIZAYOX", 2],
		["POISSIRENE", 1],
		["CHAGLAM", 4],
		["NYMPHALI", 6],
		["SANCOKI", 4],
		["OLIVINI", 9],
		["WIMESSIR", 8],
		["PHYLLALI", 4],
		["MELOFEE", 1],
		["FURAIGLON", 5],
		["DUNAJA", 8],
		["CHOCHODILE", 9],
		["ARAQUA", 7],
		["COLEODOME", 8],
		["KUNGFOUINE", 5],
		["DELESTIN", 9],
		["ROIGADA", 2],
		["HEATRAN", 4],
		["DIANCIE", 6],
		["LEVIATOR", 1],
		["DUNACONDA", 8],
		["VOLTOUTOU", 8],
		["TERRACOOL", 9],
		["GRONDOGUE", 9],
		["PARAS", 1],
		["FLOTILLON", 9],
		["ECREMEUH", 2],
		["POHMARMOTTE", 9],
		["VERT-DE-FER", 9],
		["PHANPY", 2],
		["TYRANOCIF", 2],
		["COUVERDURE", 5],
		["EXCELANGUE", 1],
		["ORTIDE", 1],
		["CRABAGARRE", 7],
		["TUTETEKRI", 8],
		["TOURNEGRIN", 2],
		["FLOTOUTAN", 5],
		["CANDINE", 7],
		["SAQUEDENEU", 1],
		["OTARIA", 1],
		["JUDOKRAK", 5],
		["VEMINI", 7],
		["GIGALITHE", 5],
		["POISSOROY", 1],
		["NIGIRIGON", 9],
		["ABRA", 1],
		["DIMOCLES", 6],
		["KRAKOS", 8],
		["LIMASPEED", 5],
		["FEURISSON", 2],
		["THEFFROYABLE", 9],
		["LIMONDE", 5],
		["GALEKING", 3],
		["MELANCOLUX", 5],
		["PHIONE", 4],
		["RAMOLOSS", 1],
		["POLARHUME", 5],
		["PIKACHU", 1],
		["GOUPIX", 1],
		["LAINERGIE", 2],
		["SCALPION", 5],
		["FORGERETTE", 9],
		["GALIFEU", 3],
		["MASKADRA", 3],
		["CROAPORAL", 6],
		["RAICHU", 1],
		["YANMA", 2],
		["DOFIN", 9],
		["CLITICLIC", 5],
		["KAORINE", 3],
		["MALVALAME", 9],
		["FLAMOUTAN", 5],
		["ROUSSIL", 6],
		["PARASECT", 1],
		["ZYGARDE", 6],
		["CHINCHIDOU", 5],
		["TENTACOOL", 1],
		["DRACOLOSSE", 1],
		["SCARABRUTE", 1],
		["LEUPHORIE", 2],
		["SPIRITOMB", 4],
		["NIRONDELLE", 3],
		["TAUROS", 1],
		["LEWSOR", 5],
		["SULFURA", 1],
		["DRABY", 3],
		["URSARING", 2],
		["NOEUNOEUF", 1],
		["PORYGON-Z", 4],
		["LIPPOUTOU", 1],
		["SORBOUBOUL", 5],
		["RELICANTH", 3],
		["M. MIME", 1],
		["LANSSORIEN", 8],
		["HELIONCEAU", 6],
		["VERPOM", 8],
		["MEWTWO", 1],
		["FANTOMINUS", 1],
		["FRAGROIN", 9],
		["TETAMPOULE", 9],
		["HAYDAIM", 5],
		["BEBECAILLE", 7],
		["HYPOTREMPE", 1],
		["BEKIPAN", 3],
		["MELOKRIK", 4],
		["POLICHOMBR", 3],
		["GRIKNOT", 4],
		["CHENIPAN", 1],
		["CADOIZO", 2],
		["NOARFANG", 2],
		["VENALGUE", 6],
		["GALVAGLA", 8],
		["TRIOXHYDRE", 5],
		["ETHERNATOS", 8],
		["MARSHADOW", 7],
		["MILOBELLUS", 3],
		["MORPEKO", 8],
		["BADABOUIN", 8],
		["SIMULARBRE", 2],
		["TAPATOES", 9],
		["POULPAF", 8],
		["ROUCOUPS", 1],
		["LANCARGOT", 5],
		["LUGULABRE", 5],
		["VIVALDAIM", 5],
		["CROCRODIL", 2],
		["ZAPETREL", 9],
		["CAPIDEXTRE", 4],
		["TARPAUD", 2],
		["CHEF-DE-FER", 9],
		["VENIPATTE", 5],
		["MATELOUTRE", 5],
		["NEGAPI", 3],
		["TRITOX", 7],
		["DRACKHAUS", 3],
		["MONAFLEMIT", 3],
		["TENTACRUEL", 1],
		["KIRLIA", 3],
		["LUMINEON", 4],
		["ETOURAPTOR", 4],
		["FULGURIS", 5],
		["POSIPI", 3],
		["HYDRAGON", 8],
		["CHELOURS", 7],
		["CERFROUSSE", 2],
		["MANGLOUTON", 7],
		["ROSELIA", 3],
		["MEIOS", 5],
		["RONDOUDOU", 1],
		["CARMACHE", 4],
		["TOMBERRO", 9],
		["DRACO", 1],
		["MELMETAL", 7],
		["FLOTTE-MECHE", 9],
		["DRACAUFEU", 1],
		["MYSDIBULE", 3],
		["MORPHEO", 3],
		["PHARAMP", 2],
		["FARFURET", 2],
		["MIAOUSS", 1],
		["CANARTICHO", 1],
		["MONTHRACITE", 8],
		["ZACIAN", 8],
		["CHLOROBULE", 5],
		["POLTHEGEIST", 8],
		["CHAMALLOT", 3],
		["MAGICARPE", 1],
		["ROTOTAUPE", 5],
		["SCARHINO", 2],
		["PEREGRAIN", 6],
		["BAOJIAN", 9],
		["BLINDALYS", 3],
		["NEMELIOS", 6],
		["BLIZZEVAL", 8],
		["TOGEKISS", 4],
		["WUSHOURS", 8],
		["LUCANON", 7],
		["BAZOUCAN", 7],
		["HYPNOMADE", 1],
		["MINISANGE", 8],
		["OKEOKE", 3],
		["BAGGIGUANE", 5],
		["ROUE-DE-FER", 9],
		["RAPASDEPIC", 1],
		["SHAYMIN", 4],
		["FLORAVOL", 2],
		["GRELACON", 6],
		["FELINFERNO", 7],
		["HOTTE-DE-FER", 9],
		["ZEKROM", 5],
		["SARMURAI", 7],
		["AFLAMANOIR", 5],
		["POLAGRIFFE", 5],
		["JIRACHI", 3],
		["CHARMINA", 3],
		["GRAVALANCH", 1],
		["PARAGRUEL", 8],
		["PORYGON", 1],
		["ETOURVOL", 4],
		["DODOALA", 7],
		["PSYKOKWAK", 1],
		["BARBICHA", 3],
		["DINGLU", 9],
		["ARROZARD", 8],
		["TISSENBOULE", 9],
		["BRAISILLON", 6],
		["AMPHINOBI", 6],
		["FORTUSIMIA", 9],
		["MIME JR.", 4],
		["VIPELIERRE", 5],
		["POUSSACHA", 9],
		["KYOGRE", 3],
		["GALOPA", 1],
		["BLIZZAROI", 4],
		["AZUMARILL", 2],
		["REGICE", 3],
		["BROUHABAM", 3],
		["CHARBI", 8],
		["MANTERNEL", 5],
		["BAMBOISELLE", 7],
		["MEDITIKKA", 3],
		["LUXIO", 4],
		["GOINFREX", 4],
		["DELCATTY", 3],
		["CAMERUPT", 3],
		["ZAMAZENTA", 8],
		["CHOVSOURIR", 5],
		["GAULET", 5],
		["GORYTHMIC", 8],
		["XATU", 2],
		["CHAPIGNON", 3],
		["COIFFETON", 9],
		["DISPAREPTIL", 8],
		["CAPUMAIN", 2],
		["SCRUTELLA", 5],
		["ALTARIA", 3],
		["FOUINAR", 2],
		["FRAGILADY", 5],
		["PSYSTIGRI", 6],
		["CERBYLLIN", 8],
		["FORT-IVOIRE", 9],
		["CARABING", 5],
		["SMOGOGO", 1],
		["REGISTEEL", 3],
		["CHEVROUM", 6],
		["PAPILORD", 4],
		["FANTYRM", 8],
		["DEUSOLOURDO", 9],
		["MANAPHY", 4],
		["FAMIGNOL", 9],
		["KABUTO", 1],
		["RAIKOU", 2],
		["DODRIO", 1],
		["KYUREM", 5],
		["RHINOFEROS", 1],
		["TYLTON", 3],
		["DARKRAI", 4],
		["CHENIPOTTE", 3],
		["PALKIA", 4],
		["MAGNEZONE", 4],
		["SNUBBULL", 2],
		["MACKOGNEUR", 1],
		["NIDORINO", 1],
		["CABRIOLAINE", 6],
		["FLAMIGATOR", 9],
		["SHAOFOUINE", 5],
		["NEITRAM", 5],
		["ELECTRODE", 1],
		["MEDHYENA", 3],
		["GIRATINA", 4],
		["GRORET", 3],
		["COMPAGNOL", 9],
		["IXON", 8],
		["KAPOERA", 2],
		["MASTOUFFE", 5],
		["SPECTREVAL", 8],
		["SPODODO", 7],
		["PAPILUSION", 1],
		["LILIA", 3],
		["GALEKID", 3],
		["PINGOLEON", 4],
		["SCOVILAIN", 9],
		["RUBOMBELLE", 7],
		["RACAILLOU", 1],
		["M. GLAQUETTE", 8],
		["FLORAMANTIS", 7],
		["MUCUSCULE", 6],
		["PREDASTERIE", 7],
		["ROUCOOL", 1],
		["VROMBOTOR", 9],
		["HURLE-QUEUE", 9],
		["FLUVETIN", 6],
		["RAFFLESIA", 1],
		["MAGMAR", 1],
		["ECAID", 7],
		["QWILFISH", 2],
		["DYNAVOLT", 3],
		["CHONGJIAN", 9],
		["TIPLOUF", 4],
		["TYPE:0", 7],
		["LIANAJA", 5],
		["GLOUPTI", 3],
		["NIDOQUEEN", 1],
		["TUTAFEH", 5],
		["SALARSEN", 8],
		["CARAPAGOS", 5],
		["BARLOCHE", 3],
		["BOREAS", 5],
		["ZEROID", 7],
		["TOUTOMBE", 9],
		["PYROBUT", 8],
		["CHIMPENFEU", 4],
		["MOUSCOTO", 7],
		["LATIOS", 3],
		["DEMANTA", 2],
		["ARCHEODONG", 4],
		["TERRAKIUM", 5],
		["TARTARD", 1],
		["MOYADE", 5],
		["TROMPIGNON", 5],
		["TARINOR", 3],
		["LUMIVOLE", 3],
		["ROITIFLAM", 5],
		["QUEULORIOR", 2],
		["MISTIGRIX", 6],
		["LOUPIO", 2],
		["GOBOU", 3],
		["MOUSTILLON", 5],
		["MUNJA", 3],
		["LEBOULEROU", 9],
		["HEXAGEL", 5],
		["SUCREINE", 7],
		["OUISTEMPO", 8],
		["FELICANIS", 9],
		["PIMITO", 9],
		["APIREINE", 4],
		["BROCELOME", 6],
		["TERAPAGOS", 9],
		["BERSERKATT", 8],
		["GROTICHON", 5],
		["ELEKTEK", 1],
		["CORAYOME", 8],
		["LOCKPIN", 4],
		["PARECOOL", 3],
		["GOURMELET", 9],
		["TOXIZAP", 8],
		["SPINDA", 3],
		["GALLAME", 4],
		["ZORUA", 5],
		["PASSEROUGE", 6],
		["OHMASSACRE", 5],
		["ARBOLIVA", 9],
		["TARSAL", 3],
		["GROLEM", 1],
		["MUSTEFLOTT", 4],
		["GERMECLAT", 9],
		["COBALTIUM", 5],
		["FEU-PERCANT", 9],
		["COXYCLAQUE", 2],
		["AMOVENUS", 8],
		["TRITONDE", 5],
		["VOLCAROPOD", 2],
		["ARGOUSTE", 7],
		["TIBOUDET", 7],
		["KRAVARECH", 6],
		["NINGALE", 3],
		["FERDETER", 9],
		["OUVRIFIER", 5],
		["CRADOPAUD", 4],
		["BOMBYDOU", 7],
		["MUSHANA", 5],
		["HEXADRON", 8],
		["OLIVADO", 9],
		["DRAKKARMIN", 5],
		["MIRADAR", 5],
		["PIFEUIL", 3],
		["CANCRELOVE", 7],
		["MOTISMA", 4],
		["KAIMORSE", 3],
		["SCOBOLIDE", 5],
		["MAGNETON", 1],
		["DURALUGON", 8],
		["BARPAU", 3],
		["MANDRILLON", 7],
		["HERBIZARRE", 1],
		["CROQUINE", 7],
		["GRODRIVE", 4],
		["AMASSEL", 9],
		["ELEKID", 2],
		["SEVIPER", 3],
		["NOADKOKO", 1],
		["EMBROCHET", 8],
		["URSAKING", 8],
		["COCHIGNON", 2],
		["WATTOUAT", 2],
		["VIGOROTH", 3],
		["RUGIT-LUNE", 9],
		/*["ABO", 1],
		["MEW", 1],
		["TIC", 5],*/
	] as [string, number][]);

	public static readonly DictionnaireEN: Map<string, number> = new Map<string, number>([
		["KINGDRA",2],
		["SIMISAGE",5],
		["GIMMIGHOUL",9],
		["ODDISH",1],
		["SURSKIT",3],
		["HELIOPTILE",6],
		["RESHIRAM",5],
		["LINOONE",3],
		["LANTURN",2],
		["LURANTIS",7],
		["MIGHTYENA",3],
		["WOOLOO",8],
		["SKARMORY",2],
		["ARCTOZOLT",8],
		["CROCONAW",2],
		["SNUBBULL",2],
		["HYDRAPPLE",9],
		["GUZZLORD",7],
		["GOODRA",6],
		["SNEASEL",2],
		["ARBOK",1],
		["SILVALLY",7],
		["CAPSAKID",9],
		["EKANS",1],
		["GROTLE",4],
		["WATTREL",9],
		["MISMAGIUS",4],
		["PAWMOT",9],
		["DREEPY",8],
		["WATCHOG",5],
		["FLYGON",3],
		["TAPU KOKO",7],
		["MASCHIFF",9],
		["HUNTAIL",3],
		["TERAPAGOS",9],
		["DEINO",5],
		["DONDOZO",9],
		["SPOINK",3],
		["PHEROMOSA",7],
		["FRIGIBAX",9],
		["RIOLU",4],
		["VOLBEAT",3],
		["CRADILY",3],
		["SWALOT",3],
		["EXCADRILL",5],
		["WURMPLE",3],
		["MAMOSWINE",4],
		["PORYGON",1],
		["MINUN",3],
		["KILOWATTREL",9],
		["PIGNITE",5],
		["MEOWSCARADA",9],
		["WARTORTLE",1],
		["PETILIL",5],
		["DUDUNSPARCE",9],
		["DRATINI",1],
		["SENTRET",2],
		["BLITZLE",5],
		["RAGING BOLT",9],
		["LOMBRE",3],
		["YAMASK",5],
		["SPIRITOMB",4],
		["FARFETCH'D",1],
		["MOTHIM",4],
		["TENTACRUEL",1],
		["YVELTAL",6],
		["SILCOON",3],
		["GLISCOR",4],
		["PANSEAR",5],
		["WALKING WAKE",9],
		["SCOLIPEDE",5],
		["MILTANK",2],
		["MARILL",2],
		["DRAPION",4],
		["ZWEILOUS",5],
		["BEARTIC",5],
		["MARSHADOW",7],
		["RELICANTH",3],
		["ILLUMISE",3],
		["FURRET",2],
		["FOONGUS",5],
		["SOBBLE",8],
		["FERROSEED",5],
		["ARIADOS",2],
		["PIPLUP",4],
		["SERVINE",5],
		["FOMANTIS",7],
		["GOURGEIST",6],
		["FLABEBE",6],
		["CHESPIN",6],
		["GHOLDENGO",9],
		["LECHONK",9],
		["DREDNAW",8],
		["SLITHER WING",9],
		["MANDIBUZZ",5],
		["REVAVROOM",9],
		["LARVITAR",2],
		["SNOM",8],
		["KLINK",5],
		["ANORITH",3],
		["RAYQUAZA",3],
		["IVYSAUR",1],
		["OINKOLOGNE",9],
		["KECLEON",3],
		["GIBLE",4],
		["BELLIBOLT",9],
		["SUICUNE",2],
		["TOXEL",8],
		["CELEBI",2],
		["VAPOREON",1],
		["SWOOBAT",5],
		["FLETCHINDER",6],
		["ORICORIO",7],
		["BEAUTIFLY",3],
		["BUNNELBY",6],
		["GYARADOS",1],
		["ZEBSTRIKA",5],
		["YANMA",2],
		["DIALGA",4],
		["CHARJABUG",7],
		["ARROKUDA",8],
		["RAIKOU",2],
		["GLIMMET",9],
		["THROH",5],
		["SHROOMISH",3],
		["TOGEPI",2],
		["GROVYLE",3],
		["GEODUDE",1],
		["TORCHIC",3],
		["CACNEA",3],
		["WOOPER",2],
		["MIMIKYU",7],
		["COFAGRIGUS",5],
		["CLAWITZER",6],
		["ZUBAT",1],
		["DRAGONAIR",1],
		["HAXORUS",5],
		["PYROAR",6],
		["CARKOL",8],
		["PANGORO",6],
		["KROOKODILE",5],
		["DUCKLETT",5],
		["REGIGIGAS",4],
		["CLAMPERL",3],
		["MILOTIC",3],
		["PERSIAN",1],
		["ROOKIDEE",8],
		["AIPOM",2],
		["ROGGENROLA",5],
		["VULPIX",1],
		["FERALIGATR",2],
		["ARCHALUDON",9],
		["QUILLADIN",6],
		["QWILFISH",2],
		["STAKATAKA",7],
		["ABRA",1],
		["CHESNAUGHT",6],
		["SWIRLIX",6],
		["BEHEEYEM",5],
		["SWELLOW",3],
		["FROAKIE",6],
		["MEGANIUM",2],
		["CUTIEFLY",7],
		["WEEZING",1],
		["DIANCIE",6],
		["CORPHISH",3],
		["MUDKIP",3],
		["DUSTOX",3],
		["CUBONE",1],
		["YUNGOOS",7],
		["CRANIDOS",4],
		["DUGTRIO",1],
		["HELIOLISK",6],
		["SQUAWKABILLY",9],
		["VICTREEBEL",1],
		["EISCUE",8],
		["NATU",2],
		["KLAWF",9],
		["TOEDSCOOL",9],
		["HAWLUCHA",6],
		["HAKAMO-O",7],
		["MEWTWO",1],
		["SHIINOTIC",7],
		["HOOPA",6],
		["KABUTOPS",1],
		["ESCAVALIER",5],
		["TOXICROAK",4],
		["BUIZEL",4],
		["JANGMO-O",7],
		["HAPPINY",4],
		["KAKUNA",1],
		["POLIWHIRL",1],
		["LOPUNNY",4],
		["ROLYCOLY",8],
		["ROSELIA",3],
		["LILLIPUP",5],
		["WHISCASH",3],
		["QUAXLY",9],
		["REGISTEEL",3],
		["VIKAVOLT",7],
		["SAWSBUCK",5],
		["BRAMBLIN",9],
		["VILEPLUME",1],
		["SCATTERBUG",6],
		["VOLTORB",1],
		["DRAGALGE",6],
		["HOUNDOOM",2],
		["SANDY SHOCKS",9],
		["SEVIPER",3],
		["MACHAMP",1],
		["ARCTIBAX",9],
		["WINGULL",3],
		["CARVANHA",3],
		["CHARCADET",9],
		["IRON MOTH",9],
		["WALREIN",3],
		["WHISMUR",3],
		["APPLETUN",8],
		["NECROZMA",7],
		["KIRLIA",3],
		["CYCLIZAR",9],
		["STEENEE",7],
		["SEADRA",1],
		["CARNIVINE",4],
		["FLOETTE",6],
		["BULBASAUR",1],
		["CACTURNE",3],
		["BIBAREL",4],
		["NAGANADEL",7],
		["GLACEON",4],
		["BINACLE",6],
		["NUZLEAF",3],
		["BUZZWOLE",7],
		["KYOGRE",3],
		["ARCHEN",5],
		["VAROOM",9],
		["SCIZOR",2],
		["RHYHORN",1],
		["STUNFISK",5],
		["MEOWSTIC",6],
		["REGIDRAGO",8],
		["WIGGLYTUFF",1],
		["GALVANTULA",5],
		["TANGELA",1],
		["PRIMARINA",7],
		["TAUROS",1],
		["VOLCARONA",5],
		["TSAREENA",7],
		["ETERNATUS",8],
		["SCORBUNNY",8],
		["CHEWTLE",8],
		["LARVESTA",5],
		["SCRAFTY",5],
		["ELGYEM",5],
		["BOLDORE",5],
		["NYMBLE",9],
		["TIRTOUGA",5],
		["TRUBBISH",5],
		["PANSAGE",5],
		["SANDYGAST",7],
		["LEDIAN",2],
		["TAPU BULU",7],
		["NIDORINO",1],
		["CUFANT",8],
		["MAKUHITA",3],
		["CUBCHOO",5],
		["SEEDOT",3],
		["EMBOAR",5],
		["VIRIZION",5],
		["TREECKO",3],
		["SKITTY",3],
		["VIBRAVA",3],
		["BANETTE",3],
		["ELDEGOSS",8],
		["SLAKING",3],
		["RABOOT",8],
		["SEALEO",3],
		["NIDOQUEEN",1],
		["HEATRAN",4],
		["GOSSIFLEUR",8],
		["DUNSPARCE",2],
		["LUNALA",7],
		["MANKEY",1],
		["ARON",3],
		["AMOONGUSS",5],
		["GOLISOPOD",7],
		["CALYREX",8],
		["OVERQWIL",8],
		["MABOSSTIFF",9],
		["BLASTOISE",1],
		["HATENNA",8],
		["FEAROW",1],
		["CLAUNCHER",6],
		["PACHIRISU",4],
		["QUAQUAVAL",9],
		["DUSCLOPS",3],
		["DRILBUR",5],
		["DODRIO",1],
		["FERROTHORN",5],
		["TURTONATOR",7],
		["ARMALDO",3],
		["RUNERIGUS",8],
		["SHUCKLE",2],
		["CRAMORANT",8],
		["IMPIDIMP",8],
		["COTTONEE",5],
		["VULLABY",5],
		["GRUMPIG",3],
		["NIDOKING",1],
		["VENONAT",1],
		["MIME JR.",4],
		["LILLIGANT",5],
		["LEAFEON",4],
		["SLOWBRO",1],
		["SPRIGATITO",9],
		["BAYLEEF",2],
		["BOUNSWEET",7],
		["REUNICLUS",5],
		["SIZZLIPEDE",8],
		["TYRUNT",6],
		["MELTAN",7],
		["ALTARIA",3],
		["TANGROWTH",4],
		["SPEWPA",6],
		["TINKATON",9],
		["REGIELEKI",8],
		["SKRELP",6],
		["TANDEMAUS",9],
		["ENAMORUS",8],
		["SALAMENCE",3],
		["REGICE",3],
		["SWINUB",2],
		["GENGAR",1],
		["BRIONNE",7],
		["URSALUNA",8],
		["CINDERACE",8],
		["HIPPOWDON",4],
		["DRIZZILE",8],
		["GLAMEOW",4],
		["PIDOVE",5],
		["SINISTCHA",9],
		["THUNDURUS",5],
		["DROWZEE",1],
		["STOUTLAND",5],
		["HAUNTER",1],
		["CHANDELURE",5],
		["GOGOAT",6],
		["COPPERAJAH",8],
		["OMANYTE",1],
		["ZAMAZENTA",8],
		["MAGCARGO",2],
		["PIDGEOT",1],
		["FALINKS",8],
		["BEWEAR",7],
		["NOCTOWL",2],
		["PRINPLUP",4],
		["BUTTERFREE",1],
		["KINGLER",1],
		["ALAKAZAM",1],
		["FARIGIRAF",9],
		["TYNAMO",5],
		["MAREEP",2],
		["ARCTOVISH",8],
		["SHINX",4],
		["TOXTRICITY",8],
		["PECHARUNT",9],
		["ZORUA",5],
		["WAILMER",3],
		["VESPIQUEN",4],
		["DIPPLIN",9],
		["HITMONLEE",1],
		["BOLTUND",8],
		["PIKACHU",1],
		["KINGAMBIT",9],
		["LATIOS",3],
		["AVALUGG",6],
		["HITMONCHAN",1],
		["SKWOVET",8],
		["GOUGING FIRE",9],
		["DRAKLOAK",8],
		["RATTATA",1],
		["GLOOM",1],
		["NINJASK",3],
		["CLEFAIRY",1],
		["DRIFBLIM",4],
		["PIDGEOTTO",1],
		["EELEKTRIK",5],
		["LANDORUS",5],
		["SHARPEDO",3],
		["MAGEARNA",7],
		["ARCANINE",1],
		["ABSOL",3],
		["CYNDAQUIL",2],
		["DURALUDON",8],
		["MUSHARNA",5],
		["JIRACHI",3],
		["PALKIA",4],
		["CENTISKORCH",8],
		["BUNEARY",4],
		["PANPOUR",5],
		["TATSUGIRI",9],
		["SEISMITOAD",5],
		["SLIGGOO",6],
		["MOLTRES",1],
		["CHI-YU",9],
		["ZEKROM",5],
		["BRONZONG",4],
		["DRACOVISH",8],
		["AZUMARILL",2],
		["TADBULB",9],
		["DELIBIRD",2],
		["MAGNEMITE",1],
		["FRAXURE",5],
		["WIMPOD",7],
		["LYCANROC",7],
		["EXEGGCUTE",1],
		["DRAGONITE",1],
		["SHELLDER",1],
		["POIPOLE",7],
		["EEVEE",1],
		["PROBOPASS",4],
		["KRABBY",1],
		["CORVIKNIGHT",8],
		["SINISTEA",8],
		["TORTERRA",4],
		["SABLEYE",3],
		["INTELEON",8],
		["DUSKULL",3],
		["IRON HANDS",9],
		["PORYGON2",2],
		["SNOVER",4],
		["BLACEPHALON",7],
		["CASTFORM",3],
		["SANDACONDA",8],
		["MISDREAVUS",2],
		["GOLURK",5],
		["NINETALES",1],
		["YAMPER",8],
		["PAWMI",9],
		["MESPRIT",4],
		["DEOXYS",3],
		["BARBOACH",3],
		["MAROWAK",1],
		["TYROGUE",2],
		["BALTOY",3],
		["VANILLUXE",5],
		["ENTEI",2],
		["DRAMPA",7],
		["SANDSLASH",1],
		["GOLBAT",1],
		["APPLIN",8],
		["GARBODOR",5],
		["SMOOCHUM",2],
		["IRON CROWN",9],
		["SIMIPOUR",5],
		["WEEPINBELL",1],
		["SWAMPERT",3],
		["HOUNDSTONE",9],
		["BEEDRILL",1],
		["FUECOCO",9],
		["FLOATZEL",4],
		["CROAGUNK",4],
		["GABITE",4],
		["GLALIE",3],
		["MARACTUS",5],
		["ELECTRIKE",3],
		["ORANGURU",7],
		["SEAKING",1],
		["ONIX",1],
		["BAXCALIBUR",9],
		["QUAGSIRE",2],
		["KLANG",5],
		["HEATMOR",5],
		["MAGMAR",1],
		["TOTODILE",2],
		["COMBEE",4],
		["SALAZZLE",7],
		["HOOTHOOT",2],
		["WYRDEER",8],
		["LITLEO",6],
		["YANMEGA",4],
		["ZOROARK",5],
		["TYPE: NULL",7],
		["GOTHITELLE",5],
		["ZARUDE",8],
		["ESPATHRA",9],
		["UNFEZANT",5],
		["MARSHTOMP",3],
		["NIDORINA",1],
		["BELDUM",3],
		["GIRAFARIG",2],
		["CARRACOSTA",5],
		["ELECTIVIRE",4],
		["GLASTRIER",8],
		["SUNFLORA",2],
		["CORSOLA",2],
		["DARMANITAN",5],
		["CLOBBOPUS",8],
		["CATERPIE",1],
		["DEERLING",5],
		["SNORLAX",1],
		["DIGLETT",1],
		["SAWK",5],
		["AURORUS",6],
		["SPINDA",3],
		["MUNCHLAX",4],
		["INCINEROAR",7],
		["TENTACOOL",1],
		["CHIMCHAR",4],
		["DEWOTT",5],
		["BLISSEY",2],
		["JOLTIK",5],
		["DODUO",1],
		["ACCELGOR",5],
		["EELEKTROSS",5],
		["SOLOSIS",5],
		["POLITOED",2],
		["WHIRLIPEDE",5],
		["BLAZIKEN",3],
		["PRIMEAPE",1],
		["TYRANTRUM",6],
		["LUDICOLO",3],
		["IRON VALIANT",9],
		["TREVENANT",6],
		["STEELIX",2],
		["SHIFTRY",3],
		["MALAMAR",6],
		["CETITAN",9],
		["MANTINE",2],
		["TOUCANNON",7],
		["PARASECT",1],
		["SHIELDON",4],
		["SHELLOS",4],
		["BRELOOM",3],
		["FEEBAS",3],
		["TOEDSCRUEL",9],
		["HARIYAMA",3],
		["FENNEKIN",6],
		["DEWPIDER",7],
		["STONJOURNER",8],
		["UNOWN",2],
		["KADABRA",1],
		["RATICATE",1],
		["METAGROSS",3],
		["NACLI",9],
		["WOOBAT",5],
		["WOBBUFFET",2],
		["DEWGONG",1],
		["FLAAFFY",2],
		["FIDOUGH",9],
		["SIMISEAR",5],
		["MAREANIE",7],
		["INKAY",6],
		["MELOETTA",5],
		["SEWADDLE",5],
		["DRACOZOLT",8],
		["MIENFOO",5],
		["ROSERADE",4],
		["CLOYSTER",1],
		["RALTS",3],
		["SHROODLE",9],
		["RABSCA",9],
		["GREAVARD",9],
		["BARBARACLE",6],
		["SPIDOPS",9],
		["DOUBLADE",6],
		["SCRAGGY",5],
		["SPHEAL",3],
		["DUSKNOIR",4],
		["PALAFIN",9],
		["MANTYKE",4],
		["CONKELDURR",5],
		["KABUTO",1],
		["LAPRAS",1],
		["PAWNIARD",5],
		["PURUGLY",4],
		["HONCHKROW",4],
		["LITTEN",7],
		["IRON TREADS",9],
		["CROBAT",2],
		["SCREAM TAIL",9],
		["ROTOM",4],
		["LOUDRED",3],
		["ZYGARDE",6],
		["GRENINJA",6],
		["CELESTEELA",7],
		["RAMPARDOS",4],
		["HITMONTOP",2],
		["VENUSAUR",1],
		["CURSOLA",8],
		["REMORAID",2],
		["PALOSSAND",7],
		["FORRETRESS",2],
		["SHUPPET",3],
		["KLEAVOR",8],
		["WO-CHIEN",9],
		["ESPURR",6],
		["CINCCINO",5],
		["ZAPDOS",1],
		["SMOLIV",9],
		["ROARING MOON",9],
		["MAGMORTAR",4],
		["GRUBBIN",7],
		["MORELULL",7],
		["SLURPUFF",6],
		["TINKATINK",9],
		["SOLROCK",3],
		["HO-OH",2],
		["GARGANACL",9],
		["HERDIER",5],
		["PATRAT",5],
		["MANECTRIC",3],
		["LUXIO",4],
		["DEDENNE",6],
		["AROMATISSE",6],
		["CLODSIRE",9],
		["CERULEDGE",9],
		["VICTINI",5],
		["VIGOROTH",3],
		["WUGTRIO",9],
		["ARCEUS",4],
		["CHARMANDER",1],
		["CHIMECHO",3],
		["NICKIT",8],
		["POLTCHAGEIST",9],
		["FRILLISH",5],
		["MEOWTH",1],
		["SOLGALEO",7],
		["KORAIDON",9],
		["PALPITOAD",5],
		["MUDSDALE",7],
		["SILICOBRA",8],
		["TAROUNTULA",9],
		["BRUXISH",7],
		["KELDEO",5],
		["GREEDENT",8],
		["SKUNTANK",4],
		["POLIWAG",1],
		["PARAS",1],
		["STARYU",1],
		["NOSEPASS",3],
		["JOLTEON",1],
		["MEDICHAM",3],
		["TEPIG",5],
		["MR. MIME",1],
		["TAPU LELE",7],
		["SWABLU",3],
		["KYUREM",5],
		["STANTLER",2],
		["BLIPBUG",8],
		["SHAYMIN",4],
		["MR. RIME",8],
		["SKIDDO",6],
		["ELEKID",2],
		["JELLICENT",5],
		["TRAPINCH",3],
		["SCEPTILE",3],
		["MAWILE",3],
		["MUNNA",5],
		["LUGIA",2],
		["MIRAIDON",9],
		["CARBINK",6],
		["LICKILICKY",4],
		["GROOKEY",8],
		["WEEDLE",1],
		["BELLOSSOM",2],
		["CRYOGONAL",5],
		["GOLDEEN",1],
		["TALONFLAME",6],
		["SWANNA",5],
		["MUNKIDORI",9],
		["NINCADA",3],
		["ESPEON",2],
		["HOPPIP",2],
		["COALOSSAL",8],
		["DURANT",5],
		["LATIAS",3],
		["MASQUERAIN",3],
		["XATU",2],
		["NOIVERN",6],
		["GIRATINA",4],
		["GOREBYSS",3],
		["SANDSHREW",1],
		["RILLABOOM",8],
		["SYLVEON",6],
		["GOLEM",1],
		["MORPEKO",8],
		["HYDREIGON",5],
		["GLIGAR",2],
		["IRON LEAVES",9],
		["SEEL",1],
		["SPEAROW",1],
		["CHARMELEON",1],
		["MAUSHOLD",9],
		["CAMERUPT",3],
		["DRAGAPULT",8],
		["FROSLASS",4],
		["GOLETT",5],
		["ELECTABUZZ",1],
		["SAMUROTT",5],
		["PINSIR",1],
		["NIHILEGO",7],
		["LEDYBA",2],
		["SIRFETCH'D",8],
		["RAPIDASH",1],
		["CHINCHOU",2],
		["TERRAKION",5],
		["PURRLOIN",5],
		["ARTICUNO",1],
		["VENIPEDE",5],
		["MELMETAL",7],
		["POPPLIO",7],
		["BUDEW",4],
		["AZURILL",3],
		["EMPOLEON",4],
		["MACHOP",1],
		["BIDOOF",4],
		["PLUSLE",3],
		["MAGNEZONE",4],
		["CETODDLE",9],
		["PSYDUCK",1],
		["BRAIXEN",6],
		["MAGNETON",1],
		["STARMIE",1],
		["PICHU",2],
		["DARUMAKA",5],
		["PYUKUMUKU",7],
		["DUBWOOL",8],
		["FROGADIER",6],
		["NACLSTACK",9],
		["STUFFUL",7],
		["SIGILYPH",5],
		["DACHSBUN",9],
		["GARDEVOIR",3],
		["STARAPTOR",4],
		["STUNKY",4],
		["MAGBY",2],
		["SMEARGLE",2],
		["PUMPKABOO",6],
		["PASSIMIAN",7],
		["PAWMO",9],
		["IRON BUNDLE",9],
		["REGIROCK",3],
		["HATTERENE",8],
		["LIEPARD",5],
		["OKIDOGI",9],
		["GRAFAIAI",9],
		["WHIMSICOTT",5],
		["GARCHOMP",4],
		["FLAREON",1],
		["GIGALITH",5],
		["GALLADE",4],
		["KRICKETUNE",4],
		["POLIWRATH",1],
		["TOGEDEMARU",7],
		["KOMMO-O",7],
		["CLEFFA",2],
		["DELPHOX",6],
		["MONFERNO",4],
		["EXEGGUTOR",1],
		["IRON JUGULIS",9],
		["FROSMOTH",8],
		["FLITTLE",9],
		["WYNAUT",3],
		["THIEVUL",8],
		["SANDILE",5],
		["TYMPOLE",5],
		["SNORUNT",3],
		["DRIFLOON",4],
		["KARRABLAST",5],
		["SPINARAK",2],
		["VIVILLON",6],
		["TORNADUS",5],
		["AGGRON",3],
		["TAPU FINI",7],
		["KOMALA",7],
		["TOGETIC",2],
		["BRAMBLEGHAST",9],
		["CHATOT",4],
		["TING-LU",9],
		["COSMOEM",7],
		["ARCHEOPS",5],
		["TYRANITAR",2],
		["BURMY",4],
		["ELECTRODE",1],
		["KUBFU",8],
		["RUFFLET",5],
		["PILOSWINE",2],
		["MINIOR",7],
		["COSMOG",7],
		["SPECTRIER",8],
		["AMPHAROS",2],
		["SHELGON",3],
		["PHIONE",4],
		["TROPIUS",3],
		["XURKITREE",7],
		["TYPHLOSION",2],
		["AXEW",5],
		["DWEBBLE",5],
		["LOKIX",9],
		["CRABOMINABLE",7],
		["HONEDGE",6],
		["KLINKLANG",5],
		["FLORGES",6],
		["FEZANDIPITI",9],
		["ABOMASNOW",4],
		["MAGIKARP",1],
		["SKORUPI",4],
		["DELCATTY",3],
		["WORMADAM",4],
		["CHARIZARD",1],
		["SUDOWOODO",2],
		["TORKOAL",3],
		["URSHIFU",8],
		["SERPERIOR",5],
		["PHANTUMP",6],
		["FLAPPLE",8],
		["PINCURCHIN",8],
		["CHERUBI",4],
		["SQUIRTLE",1],
		["ALOMOMOLA",5],
		["ZACIAN",8],
		["ZANGOOSE",3],
		["BISHARP",5],
		["GRAVELER",1],
		["NIDORAN♀",1],
		["ROCKRUFF",7],
		["XERNEAS",6],
		["SWADLOON",5],
		["PUPITAR",2],
		["GROWLITHE",1],
		["GRIMMSNARL",8],
		["DITTO",1],
		["CRAWDAUNT",3],
		["LUVDISC",3],
		["LAIRON",3],
		["DOTTLER",8],
		["POOCHYENA",3],
		["ARBOLIVA",9],
		["KARTANA",7],
		["GRIMER",1],
		["DIGGERSBY",6],
		["VANILLISH",5],
		["CHANSEY",1],
		["DOLLIV",9],
		["CRESSELIA",4],
		["CROCALOR",9],
		["GREAT TUSK",9],
		["PERRSERKER",8],
		["URSARING",2],
		["MURKROW",2],
		["HOUNDOUR",2],
		["ZIGZAGOON",3],
		["ARAQUANID",7],
		["GRAPPLOCT",8],
		["SKIPLOOM",2],
		["GOTHITA",5],
		["COMBUSKEN",3],
		["LUCARIO",4],
		["WAILORD",3],
		["SHEDINJA",3],
		["GROUDON",3],
		["BAGON",3],
		["AUDINO",5],
		["ROWLET",7],
		["CORVISQUIRE",8],
		["ANNIHILAPE",9],
		["INDEEDEE",8],
		["TEDDIURSA",2],
		["TAILLOW",3],
		["PIKIPEK",7],
		["TRUMBEAK",7],
		["DARKRAI",4],
		["SPRITZEE",6],
		["TOXAPEX",7],
		["WEAVILE",4],
		["LILEEP",3],
		["MINCCINO",5],
		["GUMSHOOS",7],
		["GOOMY",6],
		["KOFFING",1],
		["BASTIODON",4],
		["GASTRODON",4],
		["GRANBULL",2],
		["METAPOD",1],
		["OGERPON",9],
		["LAMPENT",5],
		["PELIPPER",3],
		["SALANDIT",7],
		["BELLSPROUT",1],
		["TIMBURR",5],
		["TORRACAT",7],
		["CLAYDOL",3],
		["PHANPY",2],
		["PANCHAM",6],
		["POLTEAGEIST",8],
		["FURFROU",6],
		["ALCREMIE",8],
		["KROKOROK",5],
		["WISHIWASHI",7],
		["JUMPLUFF",2],
		["GLIMMORA",9],
		["HATTREM",8],
		["UMBREON",2],
		["FLETCHLING",6],
		["RELLOR",9],
		["LOTAD",3],
		["BASCULEGION",8],
		["SUNKERN",2],
		["IRON BOULDER",9],
		["SCOVILLAIN",9],
		["CRABRAWLER",7],
		["FLAMIGO",9],
		["DECIDUEYE",7],
		["QUAXWELL",9],
		["AERODACTYL",1],
		["BRAVIARY",5],
		["BOUFFALANT",5],
		["THWACKEY",8],
		["WIGLETT",9],
		["OSHAWOTT",5],
		["HYPNO",1],
		["QUILAVA",2],
		["OMASTAR",1],
		["MIENSHAO",5],
		["BOMBIRDIER",9],
		["CHINGLING",4],
		["MEDITITE",3],
		["TINKATUFF",9],
		["LICKITUNG",1],
		["NOIBAT",6],
		["CRUSTLE",5],
		["DUOSION",5],
		["SNEASLER",8],
		["CHIEN-PAO",9],
		["BASCULIN",5],
		["RIBOMBEE",7],
		["INFERNAPE",4],
		["ORTHWORM",9],
		["LEAVANNY",5],
		["HERACROSS",2],
		["RHYDON",1],
		["FLORAGATO",9],
		["BRONZOR",4],
		["MORGREM",8],
		["CASCOON",3],
		["STARLY",4],
		["FLUTTER MANE",9],
		["JYNX",1],
		["LUNATONE",3],
		["DHELMISE",7],
		["OBSTAGOON",8],
		["TOGEKISS",4],
		["SHELMET",5],
		["NIDORAN♂",1],
		["IGGLYBUFF",2],
		["AMBIPOM",4],
		["PIDGEY",1],
		["PINECO",2],
		["BONSLY",4],
		["PONYTA",1],
		["DRUDDIGON",5],
		["GASTLY",1],
		["GOTHORITA",5],
		["BERGMITE",6],
		["MILCERY",8],
		["OCTILLERY",2],
		["VELUZA",9],
		["SNIVY",5],
		["MACHOKE",1],
		["COBALION",5],
		["TRANQUILL",5],
		["LUMINEON",4],
		["MANAPHY",4],
		["KANGASKHAN",1],
		["GULPIN",3],
		["CHIKORITA",2],
		["SKELEDIRGE",9],
		["TURTWIG",4],
		["VOLCANION",6],
		["VENOMOTH",1],
		["BRUTE BONNET",9],
		["IRON THORNS",9],
		["UXIE",4],
		["PORYGON-Z",4],
		["COMFEY",7],
		["AZELF",4],
		["CLEFABLE",1],
		["RHYPERIOR",4],
		["DARTRIX",7],
		["KRICKETOT",4],
		["SLUGMA",2],
		["CHERRIM",4],
		["NUMEL",3],
		["MUDBRAY",7],
		["SLAKOTH",3],
		["KLEFKI",6],
		["GOLDUCK",1],
		["FINIZEN",9],
		["EMOLGA",5],
		["FINNEON",4],
		["GENESECT",5],
		["STARAVIA",4],
		["ZERAORA",7],
		["JIGGLYPUFF",1],
		["RAICHU",1],
		["HORSEA",1],
		["EXPLOUD",3],
		["LITWICK",5],
		["HIPPOPOTAS",4],
		["SLOWPOKE",1],
		["BARRASKEWDA",8],
		["SCYTHER",1],
		["ORBEETLE",8],
		["LUXRAY",4],
		["METANG",3],
		["AMAURA",6],
		["DONPHAN",2],
		["SLOWKING",2],
		["AEGISLASH",6],
		["GURDURR",5],
		["ARMAROUGE",9],
		["VANILLITE",5],
		/*["MUK",1],
		["MEW",1],*/
	] as [string, number][]);

	public static readonly DictionnaireDE: Map<string, number> = new Map<string, number>([
		["ABRA",1],
		["VOLTOBAL",1],
		["GLUTEXO",1],
		["FORGITA",9],
		["VOLDI",8],
		["ZAPPLARDIN",5],
		["ENECO",3],
		["RAICHU",1],
		["HORRERBA",9],
		["EPITAFF",9],
		["PUDOX",3],
		["HOOPA",6],
		["PETZNIEF",5],
		["THANATHORA",6],
		["LEGIOS",8],
		["PELIPPER",3],
		["ICOGNITO",2],
		["PHLEGLEON",8],
		["FLAMARA",1],
		["PANPYRO",4],
		["ROLLUM",5],
		["ZEBRITZ",5],
		["CORASONN",2],
		["SCOPPEL",6],
		["STRAWICKL",5],
		["WEBARAK",2],
		["LEUFEO",6],
		["ISCALAR",6],
		["PATINARAJA",8],
		["LETARKING",3],
		["HOPPSPROSS",2],
		["RELLUK",9],
		["SALANGA",8],
		["SCHIGGY",1],
		["SUMPEX",3],
		["GUFA",7],
		["KIRLIA",3],
		["YANMEGA",4],
		["KNAKRACK",4],
		["CERAPENDRA",5],
		["BRIMANO",8],
		["SONNFEL",3],
		["MORLORD",2],
		["PHANPY",2],
		["JIUTESTO",5],
		["DRIFZEPELI",4],
		["DAMYTHIR",8],
		["LIEBISKUS",3],
		["RABAUZ",2],
		["CHIMSTIX",8],
		["WIE-SHU",5],
		["NIGIRAGI",9],
		["WALRAISA",3],
		["DARTIGNIS",6],
		["SCHWALBINI",3],
		["MASTIFIOSO",9],
		["COTTINI",8],
		["KATAGAMI",7],
		["LATIAS",3],
		["ARAQUA",7],
		["JUNGGLUT",3],
		["AZUMARILL",2],
		["ZWIRRKLOP",3],
		["OLANGAAR",8],
		["WADRIBIE",4],
		["EVOLI",1],
		["HYDRAPFEL",9],
		["INFAMOMO",9],
		["ILLUMISE",3],
		["SILEMBRIM",8],
		["MEIKRO",8],
		["HUMANOLITH",8],
		["MENKI",1],
		["ANORITH",3],
		["SNIEBEL",2],
		["MORTCHA",9],
		["KECLEON",3],
		["TRAUNMAGIL",4],
		["KARADONIS",5],
		["SCHALOKO",3],
		["KABUTOPS",1],
		["PRIMARENE",7],
		["BACKEL",9],
		["EISENFALTER",9],
		["SYMVOLARA",5],
		["RESHIRAM",5],
		["HEERASHAI",9],
		["KUPFANTI",8],
		["NOCTUH",2],
		["GUARDEVOIR",3],
		["GALAGLADI",4],
		["STARAPTOR",4],
		["GOLBIT",5],
		["SCHILLOK",1],
		["ADMURAI",5],
		["BISAKNOSP",1],
		["DRAGORAN",1],
		["VOLUMINAS",4],
		["SHUPPET",3],
		["IMPOLEON",4],
		["SCHNECKMAG",2],
		["SCHLURPLEK",4],
		["MICRICK",9],
		["DAKUMA",8],
		["ZIGZACHS",3],
		["KADABRA",1],
		["FARBEAGLE",2],
		["TARNPIGNON",5],
		["WUMMER",6],
		["BENESARU",9],
		["OCTILLERY",2],
		["SEDISAL",9],
		["ZWIEPS",9],
		["RETTAN",1],
		["NIDORINO",1],
		["MORTIPOT",8],
		["CHARMIAN",4],
		["PUPITAR",2],
		["HEITEIRA",2],
		["MAXAX",5],
		["VOLTRIANT",7],
		["AGILUZA",9],
		["HALUPENJO",9],
		["SPOINK",3],
		["MAGNAYEN",3],
		["KAPILZ",3],
		["KARNIMANI",2],
		["MAGBY",2],
		["GELATROPPO",5],
		["PARAGONI",6],
		["MONTECARBO",8],
		["VESPRIT",4],
		["ROSELIA",3],
		["MAGMAR",1],
		["TORNUPTO",2],
		["ELEKID",2],
		["PIEPI",1],
		["FLATTUTU",9],
		["DRAPFEL",8],
		["FURNIFRASS",5],
		["ARANESTRO",7],
		["TUKANON",7],
		["FELINO",2],
		["MAGEARNA",7],
		["BITHORA",6],
		["RAMEIDON",4],
		["VOLCANION",6],
		["MUNTIER",3],
		["SCHLIGDRI",9],
		["FYNX",6],
		["INFERNOPOD",8],
		["FLEKNOIL",5],
		["SANDAMER",1],
		["PAM-PAM",6],
		["BALDORFISH",2],
		["LASCHOKING",2],
		["AUSTOS",1],
		["BUMMELZ",3],
		["MEMMEON",8],
		["PAPUNGHA",2],
		["URSALUNA",8],
		["HOPPLO",8],
		["MEDITALIS",3],
		["BURMY",4],
		["BRONZEL",4],
		["LATIOS",3],
		["MAKABAJA",5],
		["AMIGENTO",7],
		["TEDDIURSA",2],
		["QUAJUTSU",6],
		["RAUPY",1],
		["REPTAIN",3],
		["GLIBUNKEL",4],
		["MAGCARGO",2],
		["GRILLCHITA",5],
		["DEPONITOX",5],
		["ANEGO",7],
		["FURIENBLITZ",9],
		["ENTORON",1],
		["UNRATUETOX",5],
		["KLIKK",5],
		["CHOREOGEL",7],
		["MEWTU",1],
		["EISENFELS",9],
		["MILTANK",2],
		["ARBOK",1],
		["ARKTILAS",6],
		["GROUDON",3],
		["SILVARRO",7],
		["FRUYAL",7],
		["CHONGJIAN",9],
		["OWEI",1],
		["KRYPPUK",4],
		["CHELTERRAR",4],
		["COSMOVUM",7],
		["SHNEBEDECK",4],
		["STARALILI",4],
		["MAMPFAXO",4],
		["DIALGA",4],
		["LILIEP",3],
		["DONPHAN",2],
		["MEDITIE",3],
		["AMOROSO",1],
		["MOGELBAUM",2],
		["GIFLOR",1],
		["DUMMIMISEL",9],
		["URGL",8],
		["SEEMON",1],
		["SABBAIONE",6],
		["ROKKAIMAN",5],
		["WAATY",2],
		["KAPU-RIKI",7],
		["DRIFTLON",4],
		["RIHORNIOR",4],
		["BOLLTERUS",4],
		["PURMEL",6],
		["ROCARA",6],
		["CHANEIRA",1],
		["PORYGON-Z",4],
		["SEEMOPS",3],
		["STREPOLI",5],
		["DARTIRI",6],
		["KRANOVIZ",8],
		["COLOSSAND",7],
		["KNACKLION",3],
		["KRONJUWILD",5],
		["HABITAK",1],
		["NOCKCHAN",1],
		["DITTO",1],
		["POTTROTT",2],
		["DIANCIE",6],
		["PINSIR",1],
		["NEBULAK",1],
		["MELMETAL",7],
		["TRAUMATO",1],
		["WABLU",3],
		["SCHEROX",2],
		["NINJASK",3],
		["FORSTELLKA",2],
		["PARFI",6],
		["SALMAGNIS",8],
		["FELILOU",5],
		["GRYPHELDIS",5],
		["VIBRAVA",3],
		["KORAIDON",9],
		["ENTON",1],
		["MAGNETILO",1],
		["PHANDRA",8],
		["GREBBIT",6],
		["MARILL",2],
		["DODU",1],
		["AQUANA",1],
		["CRYOSPINO",9],
		["SLEIMOK",1],
		["MONETIGO",9],
		["SARZENIA",1],
		["PHANTOROSS",8],
		["ISSO",3],
		["SCHNEPPKE",3],
		["PANEKON",3],
		["SIBERIO",5],
		["KIKUGI",4],
		["THERMOPOD",8],
		["KOMMANDUTAN",7],
		["PAMPROSS",7],
		["GERADAKS",3],
		["DINGLU",9],
		["PUMPDJINN",6],
		["KNARKSEL",4],
		["LANTURN",2],
		["GENGAR",1],
		["FLAMBIREX",5],
		["KANGAMA",1],
		["CHIMPEP",8],
		["PANTIFROST",8],
		["FUEGRO",7],
		["FLETIAMO",5],
		["BEATORI",9],
		["SEDIMANTUR",5],
		["RELAXO",1],
		["NECROZMA",7],
		["KUSSILLA",2],
		["ZAPPLALEK",5],
		["GAUNUX",8],
		["SIRAPFEL",9],
		["VOLTOLOS",5],
		["FINNEON",4],
		["FLUNSCHLIK",5],
		["FRIZELBLIZ",3],
		["PANTIMIMI",4],
		["MEBRANA",5],
		["SMETTBO",1],
		["AMONITAS",1],
		["NAGELOTZ",5],
		["KLINGPLIM",4],
		["EISENHALS",9],
		["NIDORINA",1],
		["VIPITIS",3],
		["STOLLRAK",3],
		["FROXY",6],
		["SCHLAPFEL",8],
		["BLIPP",9],
		["MURAMURA",7],
		["IGNIVOR",5],
		["TOHAIDO",3],
		["DRATINI",1],
		["MATRIFOL",5],
		["DUMMISEL",2],
		["GRANFORGITA",9],
		["LECTRAGON",8],
		["FLORGES",6],
		["XERNEAS",6],
		["FERKOKEL",5],
		["BRITZIGEL",8],
		["MELTAN",7],
		["METAGROSS",3],
		["DURENGARD",6],
		["FOLIKON",5],
		["LAMPI",2],
		["SCHLAPOR",4],
		["SNIEBOSS",8],
		["FRIEDWUFF",9],
		["GLUMANDA",1],
		["MAGBRANT",4],
		["YUYU",9],
		["PANZAERON",2],
		["PANFLAM",4],
		["ARMALDO",3],
		["SENSECT",8],
		["ALGITT",6],
		["ZORUA",5],
		["METENO",7],
		["FLOETTE",6],
		["ENEKORO",3],
		["EISENRAD",9],
		["KEILFLAMME",9],
		["KINDWURM",3],
		["SWARONESS",5],
		["SERPIFEU",5],
		["FLAMINKNO",9],
		["FLEMMLI",3],
		["TRAGOSSO",1],
		["FRUBBERL",7],
		["KNATTOX",9],
		["PAPINELLA",3],
		["SCHWALBOSS",3],
		["SEN-LONG",7],
		["RIOLU",4],
		["WONNEIRA",4],
		["GOLDINI",1],
		["KOBALIUM",5],
		["SIMSALA",1],
		["IGASTARNISH",6],
		["PESCRAGON",8],
		["BAEHMON",8],
		["AFFITI",9],
		["CHEVRUMM",6],
		["STAHLOS",2],
		["REGICE",3],
		["CALAMANERO",6],
		["TERRIBARK",5],
		["BALGORAS",6],
		["KOSTURSO",7],
		["SNOBILIKAT",1],
		["ALTARIA",3],
		["SNUBBULL",2],
		["ELEZARD",6],
		["BOJELIN",4],
		["SCHLUPPUCK",3],
		["LITHOMITH",5],
		["NAVITAUB",5],
		["LUGIA",2],
		["TROMPECK",7],
		["MAKUHITA",3],
		["PYGRAULON",5],
		["HOKUMIL",8],
		["DESPOTAR",2],
		["FIARO",6],
		["CHILLABELL",5],
		["DEDENNE",6],
		["YORKLEFF",5],
		["VELURSI",7],
		["CRIMANZO",9],
		["SICHLOR",1],
		["KLIKLAK",5],
		["WINDEWOGE",9],
		["RAYQUAZA",3],
		["BONINU",9],
		["TENTACHA",1],
		["KOKUNA",1],
		["PRAKTIBALK",5],
		["SAMURZEL",3],
		["KAOCTO",8],
		["RIESENZAHN",9],
		["SHARDRAGO",5],
		["GEOROK",1],
		["LUMISPROSS",9],
		["ECHNATOLL",5],
		["COSMOG",7],
		["CELEBI",2],
		["LECRYODON",8],
		["MOPEX",9],
		["STERNDU",1],
		["MOORABBEL",3],
		["COTTOMI",8],
		["MASSKITO",7],
		["KNILZ",3],
		["KNARBON",9],
		["KUKMARDA",5],
		["SODAMAK",5],
		["HEATRAN",4],
		["FLANIWAL",9],
		["EMOLGA",5],
		["FRIGOMETRI",5],
		["SCHLIGDA",9],
		["SEEDRAKING",2],
		["ZIRPURZE",4],
		["AMFIRA",7],
		["TENTAGRA",9],
		["OMOT",1],
		["ROBBALL",7],
		["TOGEKISS",4],
		["ESPINODON",9],
		["TRAUNFUGIL",2],
		["TOXEL",8],
		["STALOBOR",5],
		["REGIGIGAS",4],
		["NOKTUSKA",3],
		["TANHEL",3],
		["SKUNKAPUH",4],
		["BISSBARK",5],
		["SHNURGARST",4],
		["PSIAU",6],
		["PSIANA",2],
		["VEGICHITA",5],
		["EISENBLATT",9],
		["LAHMUS",1],
		["VULNONA",1],
		["CLAVION",6],
		["GANOVIL",5],
		["KAPU-KIME",7],
		["TERAPAGOS",9],
		["CURELEI",7],
		["MASKEREGEN",3],
		["KRAWUMMS",3],
		["KWAKS",9],
		["QUABBEL",5],
		["KEIFEL",2],
		["FEELINARA",6],
		["POKUSAN",8],
		["BLANAS",3],
		["WINGULL",3],
		["QUAPPO",1],
		["ELEKTEK",1],
		["SKELOKROK",9],
		["ARKTOS",1],
		["GLADIANTRI",5],
		["NASGNET",3],
		["FARIGIRAF",9],
		["WAUMBOLL",5],
		["FLAUSCHLING",6],
		["BARSCHUFT",5],
		["APOQUALLYP",5],
		["KRARMOR",8],
		["LUXTRA",4],
		["SOLGALEO",7],
		["CASTELLITH",5],
		["DODRI",1],
		["FLEGMON",1],
		["DONARION",7],
		["RATTIKARL",1],
		["AMAGARGA",6],
		["MOBAI",4],
		["SOMNIVORA",5],
		["TROMBORK",6],
		["VOLTILAMM",2],
		["TECTASS",7],
		["GORGASONN",8],
		["AZUGLADIS",9],
		["KNATTATOX",9],
		["ONIX",1],
		["MEDIRAS",7],
		["RIHORN",1],
		["SCHALELLOS",4],
		["TOGETIC",2],
		["PIKACHU",1],
		["LAUKAPS",5],
		["ZAPPLARANG",5],
		["HUTSASSA",5],
		["WAUMPEL",3],
		["HUBELUPF",2],
		["LOTURZEL",3],
		["AMBIDIFFEL",4],
		["BISAFLOR",1],
		["GASTRODON",4],
		["IBITAK",1],
		["REGIELEKI",8],
		["ZWOTTRONIN",5],
		["GROLLDRA",8],
		["GROINK",3],
		["CAESURIO",5],
		["KNOSPI",4],
		["PLUSLE",3],
		["MASKAGATO",9],
		["CAMAUB",3],
		["MONARGORAS",6],
		["KLOPPTOPUS",8],
		["FAMIEPS",9],
		["RASAFF",1],
		["IGAMARO",6],
		["GIERSPENST",9],
		["IROKEX",5],
		["TENTERRA",9],
		["TANGOLOSS",4],
		["SCAMPISTO",6],
		["KYUREM",5],
		["NIDOQUEEN",1],
		["LEXTREMO",9],
		["TORTUNATOR",7],
		["PLINFA",4],
		["ZYGARDE",6],
		["FLUNKIFER",3],
		["AZURILL",3],
		["QUAXO",2],
		["NIDORAN♀",1],
		["TANDRAK",6],
		["GEWALDRO",3],
		["PIXI",1],
		["NIDORAN♂",1],
		["ZWIRRFINST",4],
		["DIGDA",1],
		["TENTANTEL",5],
		["SCHLINGKING",7],
		["STARMIE",1],
		["ARBORETOSS",7],
		["LOHGOCK",3],
		["LUMINEON",4],
		["LUNALA",7],
		["DURALUDON",8],
		["GEOSALI",9],
		["MORUDA",7],
		["GELATWINO",5],
		["VOLTULA",5],
		["WASHAKWIL",5],
		["BANETTE",3],
		["LICHTEL",5],
		["RIFFEX",8],
		["MELOETTA",5],
		["EISENHAUPT",9],
		["WULAOSU",8],
		["SKORGLA",2],
		["KINGLER",1],
		["ROTOMURF",5],
		["VOLTENSO",3],
		["MAGNETON",1],
		["RATTFRATZ",1],
		["QURTEL",3],
		["ARKANI",1],
		["WEHERBA",9],
		["MARITELLIT",8],
		["TAUBOGA",1],
		["HONWEISEL",4],
		["PESCRYODON",8],
		["BOJELIN",4],
		["PIKUDA",8],
		["ELEVOLTEK",4],
		["SESOKITZ",5],
		["TENGULIST",3],
		["BRUTALANDA",3],
		["WOINGENAU",2],
		["MASCHOCK",1],
		["CORONOSPA",8],
		["WAILMER",3],
		["EFOSERP",5],
		["BOREOS",5],
		["GELATINI",5],
		["AKKUP",7],
		["KREBSCORPS",3],
		["RABIGATOR",5],
		["FOLIPURBA",4],
		["MAGNEZONE",4],
		["REGIROCK",3],
		["KLEINSTEIN",1],
		["FLAMIAU",7],
		["PSIAUGON",6],
		["SALTIGANT",9],
		["PORENTA",1],
		["LAUCHZELOT",8],
		["VOLTREL",9],
		["KLIBBE",9],
		["UHAFNIR",6],
		["BIDIFAS",4],
		["ZWIRRLICHT",3],
		["TROPIUS",3],
		["FLABEBE",6],
		["OLIVINIO",9],
		["GIRATINA",4],
		["VEGIMAK",5],
		["FEURIGEL",2],
		["SKARABAKS",9],
		["YANMA",2],
		["SPINSIDIAS",9],
		["VULPIX",1],
		["AGOYON",7],
		["GALLOPA",1],
		["FLOINK",5],
		["SONNFLORA",2],
		["MANTIRPS",4],
		["SONNKERN",2],
		["DUOKLES",6],
		["DUFLOR",1],
		["DRAGONIR",1],
		["KATAPULDRA",8],
		["KRAMURX",2],
		["TAUROS",1],
		["KREBUTACK",3],
		["MOLLIMORBA",5],
		["XATU",2],
		["MILZA",5],
		["DELFINATOR",9],
		["WAGONG",8],
		["LOMBRERO",3],
		["SENGO",3],
		["TENTOXA",1],
		["VISCORA",6],
		["PALKIA",4],
		["SCHNUTHELM",5],
		["GENESECT",5],
		["KNOGGA",1],
		["TAUBSI",1],
		["MITODOS",5],
		["KAMEHAPS",8],
		["BANDELBY",7],
		["AMPHIZEL",6],
		["BARRAKIEFA",8],
		["BOTOGEL",2],
		["FUKANO",1],
		["FASASNOB",5],
		["MONOZYTO",5],
		["BRIDURADON",9],
		["TOBUTZ",4],
		["TANNZA",2],
		["FATALITEE",8],
		["LIBERLO",8],
		["ZAPDOS",1],
		["TYRACROC",2],
		["LAVADOS",1],
		["HIPPOPOTAS",4],
		["MACHOLLO",1],
		["LUSARDIN",7],
		["MANTIDEA",7],
		["SUELORD",9],
		["FORMEO",3],
		["KRABBY",1],
		["QUIEKEL",2],
		["FLAMPIVIAN",5],
		["AXANTOR",8],
		["KELDEO",5],
		["GARADOS",1],
		["SERVOL",8],
		["AMARINO",6],
		["MACHOMEI",1],
		["ENDIVIE",2],
		["OLITHENA",9],
		["VOLBEAT",3],
		["ZACIAN",8],
		["LATERNECTO",5],
		["GALAPAFLOS",5],
		["PIONSKORA",4],
		["BAUZ",7],
		["GRAMOKLES",6],
		["WATTZAPF",5],
		["FLAMPION",5],
		["KIESLING",5],
		["SUICUNE",2],
		["OTTARO",5],
		["ENDYNALOS",8],
		["STARAVIA",4],
		["GOLBAT",1],
		["IMPERGATOR",2],
		["BRIMOVA",8],
		["TOGEPI",2],
		["KICKLEE",1],
		["SCHLURP",1],
		["KNUDDELUFF",1],
		["SKORGRO",4],
		["BLUZUK",1],
		["SHEINUX",4],
		["SANKABUH",7],
		["PIONDRAGI",4],
		["KNOFENSA",1],
		["WAMPITZ",9],
		["AEROPTERYX",5],
		["SANDAN",1],
		["FERMICULA",5],
		["HORNLIU",1],
		["MOBTIFF",9],
		["KNIRFISH",7],
		["OHRDOCH",5],
		["KINOSO",4],
		["ELFUN",5],
		["TOXIPED",5],
		["LARVITAR",2],
		["PICOCHILLA",5],
		["WOLLY",8],
		["ENTEI",2],
		["HIPPOTERUS",4],
		["LEDYBA",2],
		["KUBUIN",8],
		["AMPHAROS",2],
		["KAUMALAT",4],
		["KAPU-TORO",7],
		["PANDIR",3],
		["LUNASTEIN",3],
		["NINCADA",3],
		["SOMNIAM",5],
		["FIFFYEN",3],
		["FLURMEL",3],
		["COIFFWAFF",6],
		["BISOFANK",5],
		["LEKTROBAL",1],
		["PAMOMAMO",9],
		["IRRBIS",6],
		["WIESOR",2],
		["MANAPHY",4],
		["SLEIMA",1],
		["SODACHITA",5],
		["TARUNDEL",9],
		["BARSCHWA",3],
		["PLIPRIN",4],
		["KAPU-FALA",7],
		["SCHLARAFFEL",8],
		["MIMIGMA",7],
		["ARKTIP",6],
		["MANTAX",2],
		["BARRIKADAX",8],
		["FLUFFELUFF",2],
		["RAFFEL",8],
		["DIGDRI",1],
		["NIDOKING",1],
		["FERKULI",9],
		["CHELCARAIN",4],
		["QUARTERMAK",7],
		["KANIVANHA",3],
		["BIBOR",1],
		["IGELAVAR",2],
		["RAIKOU",2],
		["HYDROPI",3],
		["SCHMERBE",3],
		["MIEZUNDER",7],
		["KLONKETT",8],
		["MAUZINGER",8],
		["KAGURON",7],
		["WUTPILZ",9],
		["SELFE",4],
		["ARCEUS",4],
		["PANTIMOS",1],
		["REGIDRAGO",8],
		["EGUANA",6],
		["LIBELLDRA",3],
		["GRIFFEL",2],
		["EISENDORN",9],
		["PONITA",1],
		["MORPEKO",8],
		["RUTENA",6],
		["LEDIAN",2],
		["REMORAID",2],
		["DRESSELLA",5],
		["KABUTO",1],
		["TERRAKIUM",5],
		["ZEKROM",5],
		["KARPADOR",1],
		["EF-EM",6],
		["KAMALM",8],
		["KROKEL",9],
		["MINIRAS",7],
		["GOLGANTES",5],
		["HEFEL",9],
		["LAMELLUX",7],
		["PUPPANCE",3],
		["SHAYMIN",4],
		["SAGANABYSS",3],
		["ZURROKEX",5],
		["HUNDEMON",2],
		["PANFERNO",4],
		["TAUBOSS",1],
		["ROSERADE",4],
		["BROCKOLOSS",5],
		["BLUBELLA",2],
		["MUSCHAS",1],
		["MARSHADOW",7],
		["BUBUNGUS",7],
		["FRAGRUNZ",9],
		["REGISTEEL",3],
		["AALABYSS",3],
		["NORMIFIN",9],
		["REXBLISAR",4],
		["STOLLUNIOR",3],
		["PALIMPALIM",3],
		["KLIKDIKLAK",5],
		["MEGANIE",2],
		["ZIRPEISE",4],
		["ULTRIGARIA",1],
		["PARASEK",1],
		["WOMMEL",7],
		["GEHWEIHER",3],
		["MYRAPLA",1],
		["GARSTELLA",7],
		["SCHABELLE",7],
		["BURMADAME",4],
		["TRASLA",3],
		["AGGROSTELLA",7],
		["PUMMELUFF",1],
		["LAPRAS",1],
		["PAMPULI",7],
		["KERADAR",8],
		["EISENHAND",9],
		["LOKROKO",9],
		["WUFFELS",7],
		["KNAPFEL",8],
		["POLAROSS",8],
		["PAMAMO",9],
		["SMOGMOG",1],
		["JIRACHI",3],
		["RIZEROS",1],
		["WIELIE",3],
		["WAILORD",3],
		["PARFINESSE",6],
		["METANG",3],
		["PSIOPATRA",9],
		["CUPIDOS",8],
		["KLEPTIFUX",8],
		["BIDIZA",4],
		["IMANTIS",7],
		["KLEOPARDA",5],
		["FENNEXIS",6],
		["BELLEKTRO",8],
		["VISCOGON",6],
		["YVELTAL",6],
		["FIRNONTOR",3],
		["SANDFELL",9],
		["SEEJONG",3],
		["DAMHIRPLEX",2],
		["GLURAK",1],
		["MOTTINEVA",8],
		["SCHLUKWECH",3],
		["HUNDUSTER",2],
		["SKARABORN",2],
		["PORYGON2",2],
		["MABULA",7],
		["KRAKEELO",3],
		["ZWOLLOCK",8],
		["MAMOLIDA",5],
		["CRESSELIA",4],
		["VOLTREAN",9],
		["ARIADOS",2],
		["QUAPUTZI",1],
		["OLINI",9],
		["TURTOK",1],
		["KYOGRE",3],
		["TRIKEPHALO",5],
		["CAVALANZAS",5],
		["SMOGON",1],
		["KOKOWEI",1],
		["NATU",2],
		["MYRIADOR",8],
		["RESLADERO",6],
		["ZUBAT",1],
		["LUXIO",4],
		["INTELLEON",8],
		["FELIOSPA",9],
		["KAPUNO",5],
		["GORTROM",8],
		["OGERPON",9],
		["BAOJIAN",9],
		["BISASAM",1],
		["GERONIMATZ",5],
		["SAFCON",1],
		["HARIYAMA",3],
		["MEISTAGRIF",5],
		["IKSBAT",2],
		["SCHALLQUAP",5],
		["KAPOERA",2],
		["MARACAMBA",5],
		["VICTINI",5],
		["VIRIDIUM",5],
		["KOKNODON",4],
		["STOLLOSS",3],
		["JUROB",1],
		["HYDRAGIL",5],
		["GIRAFARIG",2],
		["BRONZONG",4],
		["GOLKING",1],
		["PLAUDAGEI",4],
		["KASTADUR",5],
		["PANDAGRO",6],
		["PORYGON",1],
		["GLAZIOLA",4],
		["TUSKA",3],
		["MILOTIC",3],
		["REISSLAUS",7],
		["KOLOWAL",9],
		["PYROLEO",6],
		["KOALELU",7],
		["NINJATOM",3],
		["FUENTENTE",9],
		["TYP:NULL",7],
		["VISCARGOT",6],
		["ALPOLLO",1],
		["OGHNATOLL",8],
		["KOPPLOSIO",7],
		["VENICRO",7],
		["ZARUDE",8],
		["FLAPTERYX",5],
		["PELZEBUB",8],
		["SCHILTERUS",4],
		["PUPONCHO",6],
		["MIRAIDON",9],
		["MEGALON",5],
		["SEEPER",1],
		["ROTOM",4],
		["VIVILLON",6],
		["ZERAORA",7],
		["PERLU",3],
		["HYPNO",1],
		["SNOMNOM",8],
		["ABSOL",3],
		["FRUBAILA",7],
		["HYPNOMORBA",5],
		["KRAWELL",7],
		["BAILONDA",9],
		["NACHTARA",2],
		["MAUZI",1],
		["PICCOLENTE",5],
		["PARAS",1],
		["LIN-FU",5],
		["MARIKECK",7],
		["SKELABRA",5],
		["FELORI",9],
		["HO-OH",2],
		["MANGUNIOR",7],
		["TAFFORGITA",9],
		["SHARFAX",5],
		["FROSPINO",9],
		["BLITZA",1],
		["FLATTERHAAR",9],
		["PAMO",9],
		["KRAWALLORO",9],
		["KRABBOX",7],
		["TOGEDEMARU",7],
		["KICKERLO",8],
		["LORBLATT",2],
		["LUMIFLORA",9],
		["CHILINGEL",9],
		["GEOWAZ",1],
		["SKALLYK",5],
		["GRUFF",9],
		["SANACONDA",8],
		["MOLUNK",7],
		["SNIBUNNA",4],
		["WIESENIOR",2],
		["ZOBIRIS",3],
		["RAMOTH",5],
		["DUODINO",5],
		["LUCARIO",4],
		["LEPUMENTAS",3],
		["TANGELA",1],
		["MINUN",3],
		["BRANAWARZ",5],
		["WOLWEROCK",7],
		["URSARING",2],
		["ZYTOMEGA",5],
		["AERODACTYL",1],
		["PEPPECK",7],
		["CHELAST",4],
		["PHIONE",4],
		["CAMERUPT",3],
		["FROSDEDJE",4],
		["ZAMAZENTA",8],
		["MAMUTEL",4],
		["GECKARBOR",3],
		["KAPPALORES",3],
		["GLADIMPERIO",9],
		["ADEBOM",9],
		["MORBITESSE",5],
		["WELSAR",3],
		["LILMINIP",5],
		["MOTERPEL",4],
		["ELEZEBA",5],
		["GRILLMAK",5],
		["ZOROARK",5],
		["FATALITCHA",9],
		["SKUNTANK",4],
		["TOXIQUAK",4],
		["MAEHIKEL",6],
		["DARKRAI",4],
		["QUAPSEL",1],
		["VENUFLIBIS",4],
		["PICHU",2],
		["PACHIRISU",4],
		["DEMETEROS",5],
		["SERPIROYAL",5],
		["DUSSELGURR",5],
		["KARIPPAS",5],
		["HOOTHOOT",2],
		["DEOXYS",3],
		["SCHLURM",9],
		["ROSSANA",1],
		["KRAMSHEF",4],
		["GRANBULL",2],
		["JUGONG",1],
		["RELICANTH",3],
		["GRANDIRAS",7],
		["BRIGARON",6],
		["SPROXI",9],
		["DRASCHEL",3],
		["HASPIROR",4],
		/*["MEW",1],
		["PII",2],
		["MANGUSPEKTOR",7],
		["EISENBUENDEL",9],
		["DONNERSICHEL",9],
		["EISENKRIEGER",9],
		["BRUELLSCHWEIF",9],
		["KRIECHFLUEGEL",9],*/
	] as [string, number][]);
	
	public static readonly DictionnaireJA: Map<string, number> = new Map<string, number>([
		["ONVERN",6],
		["GARDIE",1],
		["MAMEBATTA",9],
		["DAIOUDOU",8],
		["TROPIUS",3],
		["MANTAIN",2],
		["MUSHARNA",5],
		["POKABU",5],
		["KOFUKIMUSHI",6],
		["DEATHBARN",8],
		["MEGANIUM",2],
		["GOUKAZARU",4],
		["GOLOOG",5],
		["GOTHIMU",5],
		["GOGOAT",6],
		["REGICE",3],
		["KOMATANA",5],
		["BANBADORO",7],
		["JUNAIPER",7],
		["SOUBLADES",9],
		["MIBRIM",8],
		["BALKIE",2],
		["TEKKAGUYA",7],
		["BASSRAO",5],
		["UPAH",2],
		["MAHOXY",6],
		["VIRIZION",5],
		["CUESPATRA",9],
		["GUREGGRU",4],
		["HIBANNY",8],
		["PIGEON",1],
		["PUKURIN",1],
		["KARANAKUSHI",4],
		["YANCHAM",6],
		["YOMAWARU",3],
		["KANUCHAN",9],
		["CHADEATH",9],
		["FUSHIDE",5],
		["LIZARDO",1],
		["MIMIKKYU",7],
		["MAMMOO",4],
		["APPRYU",8],
		["YUKIKABURI",4],
		["ISHIHENGIN",8],
		["EIFIE",2],
		["BEADARU",4],
		["KAPU-REHIRE",7],
		["NUMELGON",6],
		["WATASHIRAGA",8],
		["BOOBURN",4],
		["FIARROW",6],
		["BULU",2],
		["ROSERADE",4],
		["HIDOIDE",7],
		["CRESSELIA",4],
		["PURURILL",5],
		["YATOUMORI",7],
		["ACHIGATOR",9],
		["HEIGANI",3],
		["PORYGON",1],
		["COCOON",1],
		["CHANDELA",5],
		["TRIMMIEN",6],
		["NUCKRAR",3],
		["GOURTON",9],
		["AGILDER",5],
		["KUITARAN",5],
		["FUKUTHROW",7],
		["RINGUMA",2],
		["LUNALA",7],
		["BERORINGA",1],
		["NOKOCCHI",2],
		["HOHO",2],
		["DUGTRIO",1],
		["BOHMANDER",3],
		["TEKKANIN",3],
		["CHERINBO",4],
		["KARIKIRI",7],
		["HARIBORG",6],
		["AYASHISHI",8],
		["KABUTO",1],
		["DOHIDOIDE",7],
		["SPEAR",1],
		["BARUBEAT",3],
		["HARYSEN",2],
		["MOMOWAROU",9],
		["KEIKOUO",4],
		["TAMATAMA",1],
		["DODO",1],
		["MIMIZUZU",9],
		["FLORGES",6],
		["SUNANOKEGAWA",9],
		["NATY",2],
		["JIJILONG",7],
		["HULKUJIRA",9],
		["MUGENDINA",8],
		["NYAHEAT",7],
		["MEGUROCO",5],
		["KEMUSSO",3],
		["ARCEUS",4],
		["ERIKITERU",6],
		["RUFFRESIA",1],
		["MINOMUCCHI",4],
		["SAND",1],
		["TORNELOS",5],
		["DONFAN",2],
		["SUBAME",3],
		["ONISUZUME",1],
		["ZAMAZENTA",8],
		["PROTOGA",5],
		["SCOVILLAIN",9],
		["ARBOK",1],
		["ZANGOOSE",3],
		["COTOISE",3],
		["POPPO",1],
		["TAMAGETAKE",5],
		["ENNEWT",7],
		["BIPPA",4],
		["ELESON",8],
		["DARUMAKKA",5],
		["ZEKROM",5],
		["BUFFRON",5],
		["HASSBOH",3],
		["ONISHIZUKUMO",7],
		["POTTAISHI",4],
		["IWAPALACE",5],
		["NYASPER",6],
		["UNKNOWN",2],
		["FREFUWAN",6],
		["GAMENODES",6],
		["ROSELIA",3],
		["MIRUHOG",5],
		["LILYLA",3],
		["METANG",3],
		["MATADOGAS",1],
		["KOKOROMORI",5],
		["OSYAMARI",7],
		["HOUOU",2],
		["WRAITHPOS",8],
		["HORUDO",6],
		["ONONDO",5],
		["GAOGAEN",7],
		["TATSUBAY",3],
		["HATOBOH",5],
		["NAGEKI",5],
		["HABUNAKE",3],
		["CHIREAN",3],
		["DORONCH",8],
		["SIRNIGHT",3],
		["GURENARMA",9],
		["KOLINK",4],
		["PHIONE",4],
		["TAGGINGRU",9],
		["WAKKANEZUMI",9],
		["CHIONJEN",9],
		["KIBANHA",3],
		["JIBACOIL",4],
		["DOGARS",1],
		["KAPU-KOKEKO",7],
		["AMETAMA",3],
		["NYARTH",1],
		["RARECOIL",1],
		["TAIRETSU",8],
		["PERAP",4],
		["CHILLACCINO",5],
		["OHSUBAME",3],
		["VOLCANION",6],
		["MANKEY",1],
		["CHICORITA",2],
		["ZOROARK",5],
		["KAIRYU",1],
		["MASSUGUMA",3],
		["MIZUGOROU",3],
		["PIPPI",1],
		["GHOST",1],
		["GUSOKUMUSHA",7],
		["UNERUMINAMO",9],
		["SHIGAROKO",9],
		["BEROBA",8],
		["MAKENKANI",7],
		["VICTINI",5],
		["LUXIO",4],
		["EMRIT",4],
		["SAKURABYSS",3],
		["ENECO",3],
		["FORETOS",2],
		["AMAMAIKO",7],
		["PONYTA",1],
		["MINOMADAM",4],
		["TYPE: NULL",7],
		["KINGLER",1],
		["DAKUMA",8],
		["GYARADOS",1],
		["LIGRAY",5],
		["KONGPANG",1],
		["UTSUBOT",1],
		["WATACCO",2],
		["HERDERRIE",5],
		["DONGKARASU",4],
		["KUZUMO",6],
		["AMAJO",7],
		["LUCARIO",4],
		["YUKINOOH",4],
		["AOGARASU",8],
		["PATCHIRAGON",8],
		["HUNTAIL",3],
		["LAUDBON",9],
		["HIKOZARU",4],
		["YABUKURON",5],
		["WHALOH",3],
		["NIDOKING",1],
		["PAMOT",9],
		["HARABARIE",9],
		["YOKUBARISU",8],
		["ARCHEN",5],
		["SAMAYOURU",3],
		["RUNPAPPA",3],
		["ARCHEOS",5],
		["NIDOQUEEN",1],
		["ONONOKUS",5],
		["DURALUDON",8],
		["REGIELEKI",8],
		["TERAPAGOS",9],
		["TARUPPLE",8],
		["TUNDETUNDE",7],
		["TUNBEAR",5],
		["MONOZU",5],
		["SARUNORI",8],
		["TETSUNOBUJIN",9],
		["AMAKAJI",7],
		["SHIMAMA",5],
		["NAMAKOBUSHI",7],
		["KEROMATSU",6],
		["CARBOU",9],
		["HEATRAN",4],
		["THUNDER",1],
		["DONMEL",3],
		["YUKIWARASHI",3],
		["GORIRANDER",8],
		["MUCHUL",2],
		["KEKENKANI",7],
		["MADATSUBOMI",1],
		["AIRMD",2],
		["NATIO",2],
		["DIALGA",4],
		["BETBETON",1],
		["JYARAKO",7],
		["GAMAGEROGE",5],
		["YABACHA",8],
		["SEGOHRU",9],
		["KIRLIA",3],
		["VOLTOLOS",5],
		["BEEQUEN",4],
		["PRASLE",3],
		["GIGIARU",5],
		["FUWARIDE",4],
		["SIRODETHNA",7],
		["MARACACCHI",5],
		["YADON",1],
		["FOKKO",6],
		["USOKKIE",2],
		["TERRAKION",5],
		["PERFUTON",9],
		["HINBASS",3],
		["SUICUNE",2],
		["DEKAGOOSE",7],
		["ZERAORA",7],
		["MEGAYANMA",4],
		["KINOCOCO",3],
		["HINOARASHI",2],
		["MOOLAND",5],
		["NYAHOJA",9],
		["FUWANTE",4],
		["MAGMARASHI",2],
		["OHNYULA",8],
		["GABURIAS",4],
		["BUTTERFREE",1],
		["JIRACHI",3],
		["POTDEATH",8],
		["HIMEGUMA",2],
		["TATETOPS",4],
		["GOKULIN",3],
		["DESUKARN",5],
		["SUNAHEBI",8],
		["MITSUHONEY",4],
		["UDEPPOU",6],
		["GOTHIRUSELLE",5],
		["VANIPETI",5],
		["LATIOS",3],
		["KAPU-TETEFU",7],
		["AGOJIMUSHI",7],
		["RAYQUAZA",3],
		["MOTOTOKAGE",9],
		["KODORA",3],
		["ZUBAT",1],
		["KARAMINGO",9],
		["MAGGYO",5],
		["KINGDRA",2],
		["LAGLARGE",3],
		["FIRE",1],
		["GLACIA",4],
		["MOUKAZARU",4],
		["WULAOSU",8],
		["LATIAS",3],
		["DOKUKURAGE",1],
		["RIKIKIRIN",9],
		["LISYAN",4],
		["HELLGAR",2],
		["BOSSGODORA",3],
		["COKODORA",3],
		["TAMANTULA",9],
		["GLION",4],
		["SOHNANO",3],
		["TEPPOUO",2],
		["GILLGARD",6],
		["REGIDORAGO",8],
		["WAKASYAMO",3],
		["DOTEKKOTSU",5],
		["DOBLE",2],
		["RENTORAR",4],
		["HAKURYU",1],
		["MINEZUMI",5],
		["NEOLANT",4],
		["HABATAKUKAMI",9],
		["MANAPHY",4],
		["RATTA",1],
		["KIBAGO",5],
		["ALLIGATES",2],
		["KONOYOZARU",9],
		["BUNYATTO",4],
		["RAMPALD",4],
		["PARAS",1],
		["KAENJISHI",6],
		["MELOETTA",5],
		["MAHOMIL",8],
		["MAMANBOU",5],
		["NAMAZUN",3],
		["DEKANUCHAN",9],
		["DESUMASU",5],
		["SEADRA",1],
		["RAIKOU",2],
		["TUTININ",3],
		["NAETLE",4],
		["RIOLU",4],
		["CELEBI",2],
		["BAIVANILLA",5],
		["JYARARANGA",7],
		["NYOROZO",1],
		["BAOPPU",5],
		["DENTULA",5],
		["SHOWERS",1],
		["PELIPPER",3],
		["HANECCO",2],
		["SEGLAIVE",9],
		["UTSUDON",1],
		["GRANBULU",2],
		["YUXIE",4],
		["MELECIE",6],
		["HITOMOSHI",5],
		["KOJONDO",5],
		["ACEBURN",8],
		["BANGIRAS",2],
		["HAPPINAS",2],
		["HIPPOPOTAS",4],
		["PORYGON-Z",4],
		["TETSUNOISAHA",9],
		["GONYONYO",3],
		["DODOGEZAN",9],
		["DOKUCALE",3],
		["ISHIZUMAI",5],
		["FLOETTE",6],
		["KURUMIRU",5],
		["DRAMIDORO",6],
		["DOKUROG",4],
		["YABASOCHA",9],
		["NEGIGAKNIGHT",8],
		["KAMICCHU",9],
		["SHISHIKO",6],
		["CHAOBOO",5],
		["MARSHADOW",7],
		["BURSYAMO",3],
		["DOROBANKO",7],
		["THUNDERS",1],
		["ONIGOHRI",3],
		["ELEZARD",6],
		["JIMEREON",8],
		["ARUKUJIRA",9],
		["DADARIN",7],
		["IINEINU",9],
		["INOMOO",2],
		["ILLUMISE",3],
		["YOGIRAS",2],
		["MAYULD",3],
		["SHIBIRUDON",5],
		["OTOSUPUS",8],
		["POWALEN",3],
		["MOJUMBO",4],
		["WINDIE",1],
		["PEARLULU",3],
		["NENDOLL",3],
		["ZENIGAME",1],
		["GOMAZOU",2],
		["NAMAKERO",3],
		["PIKACHU",1],
		["WELKAMO",9],
		["BACHINKEY",8],
		["KURUMAYU",5],
		["VIBRAVA",3],
		["NYAONIX",6],
		["WHEEGA",5],
		["GHOS",1],
		["AGEHUNT",3],
		["SANAGIRAS",2],
		["TETSUNOIWAO",9],
		["KORAIDON",9],
		["STRIKE",1],
		["NASSY",1],
		["PTERA",1],
		["MUNNA",5],
		["SCORUPI",4],
		["SUNIGOON",8],
		["BUROROROOM",9],
		["MARUNOOM",3],
		["KAKUREON",3],
		["AMARURUGA",6],
		["BASAGIRI",8],
		["PAOJIAN",9],
		["GIRATINA",4],
		["ZORUA",5],
		["KABUTOPS",1],
		["MOKOKO",2],
		["KIRINRIKI",2],
		["BAKPHOON",2],
		["KEKKING",3],
		["LOVECUS",3],
		["TETSUNOKAINA",9],
		["BOOSTER",1],
		["AKUZIKING",7],
		["SYARITATSU",9],
		["NEMASYU",7],
		["ONBAT",6],
		["DIHEAD",5],
		["MOROBARERU",5],
		["METAGROSS",3],
		["DELVIL",2],
		["ROUGELA",1],
		["TAMANTA",4],
		["RURIRI",3],
		["TYLTTO",3],
		["DOJOACH",3],
		["YAMIRAMI",3],
		["MARUYAKUDE",8],
		["FLABEBE",6],
		["GANGAR",1],
		["GIGIGIARU",5],
		["JUGON",1],
		["ORDILE",2],
		["SHIZARIGER",3],
		["ZURUGGU",5],
		["BAOKKIE",5],
		["FUTACHIMARU",5],
		["KELDEO",5],
		["FUKAMARU",4],
		["TSUTARJA",5],
		["GARAGARA",1],
		["UOCHILLDON",8],
		["SHIBIBEEL",5],
		["YUKIHAMI",8],
		["ETEBOTH",4],
		["KAPOERER",2],
		["VANIRICH",5],
		["PHEROACHE",7],
		["YURADLE",3],
		["ELEBOO",1],
		["TRANSEL",1],
		["RALTS",3],
		["YUNGERER",1],
		["OTACHI",2],
		["DAIKENKI",5],
		["KAILIOS",1],
		["MUKKURU",4],
		["TSUTSUKERA",7],
		["BAKUUDA",3],
		["ABAGOURA",5],
		["SHIBISHIRASU",5],
		["NYOROMO",1],
		["FUSHIGISOU",1],
		["IWANKO",7],
		["AMARUS",6],
		["HIMANUTS",2],
		["YESSAN",8],
		["YAREYUUTAN",7],
		["SABONEA",3],
		["GAMAGARU",5],
		["LAPLACE",1],
		["PATCHILLDON",8],
		["ZOUDOU",8],
		["USOHACHI",4],
		["LIVOLT",3],
		["ENTEI",2],
		["DEOXYS",3],
		["HAHAKOMORI",5],
		["WOOLUU",8],
		["KAGEBOUZU",3],
		["KAMETETE",6],
		["SOLROCK",3],
		["GOBIT",5],
		["TATAKKO",8],
		["KOJIO",9],
		["TYLTALIS",3],
		["DOKKORER",5],
		["RIKUKURAGE",9],
		["NUOH",2],
		["TANEBOH",3],
		["TSUBOTSUBO",2],
		["SHELLDER",1],
		["GORONDA",6],
		["HIYAKKIE",5],
		["SHIZUKUMO",7],
		["BLIZZAPOS",8],
		["MUSKIPPA",4],
		["ARMALDO",3],
		["ARMORGA",8],
		["MAGMAG",2],
		["OGERPON",9],
		["KAIDEN",9],
		["HARYMAN",8],
		["ORACHIFU",9],
		["MASSIVOON",7],
		["SADAIJA",8],
		["PUPIMOCCHI",9],
		["AGNOME",4],
		["MILTANK",2],
		["SAWAMULAR",1],
		["ZYGARDE",6],
		["MAKUNOSHITA",3],
		["LUGIA",2],
		["DENRYU",2],
		["NONOKURAGE",9],
		["PIXY",1],
		["AIANT",5],
		["SAKEBUSHIPPO",9],
		["MIMILOP",4],
		["PERSIAN",1],
		["PENDROR",5],
		["TANDON",8],
		["KOROBOHSHI",4],
		["MORPHON",1],
		["SHIKIJIKA",5],
		["SUNNYGO",2],
		["RAKURAI",3],
		["ULGAMOTH",5],
		["DORAPULT",8],
		["XERNEAS",6],
		["HOOPA",6],
		["MASHADE",7],
		["GORIKY",1],
		["DUMBBER",3],
		["GABITE",4],
		["EMOLGA",5],
		["DOHMIRROR",4],
		["YAMIKARASU",2],
		["DAINOSE",4],
		["ASHIMARI",7],
		["REDOMUSHI",8],
		["TOGEPY",2],
		["NUMERA",6],
		["MERRIEP",2],
		["DUSTDAS",5],
		["SLEEPE",1],
		["YVELTAL",6],
		["MINIRYU",1],
		["WARRGLE",5],
		["YONOIR",4],
		["CALAMANERO",6],
		["BERACAS",9],
		["GOLONYA",1],
		["NUIKOGUMA",7],
		["LUGARUGAN",7],
		["KAMEIL",1],
		["YANAKKIE",5],
		["NOKOKOCCHI",9],
		["MUMARGI",4],
		["KOFUURAI",6],
		["JIODUMU",9],
		["OMSTAR",1],
		["KENTAUROS",1],
		["NUKENIN",3],
		["KUSAIHANA",1],
		["EOLB",8],
		["HARIMARON",6],
		["TATTU",1],
		["TAIKAIDEN",9],
		["YIYUI",9],
		["ABULY",7],
		["LEAFIA",4],
		["DOHTAKUN",4],
		["CHIWOHAUHANE",9],
		["NAZONOKUSA",1],
		["MASQUERNYA",9],
		["GOLDUCK",1],
		["BARRIERD",1],
		["CLEFFY",6],
		["PAMO",9],
		["ITOMARU",2],
		["DARKRAI",4],
		["ABSOL",3],
		["ENEKORORO",3],
		["BANEBOO",3],
		["MAWHIP",8],
		["BOCHI",9],
		["OHROT",6],
		["STRINDER",8],
		["BETBETER",1],
		["YARUKIMONO",3],
		["UNIRAN",5],
		["GOTHIMIRU",5],
		["GANTLE",5],
		["ODOSHISHI",2],
		["MANYULA",4],
		["CAPSAIJI",9],
		["ANOHORAGUSA",9],
		["GROUDON",3],
		["IDAINAKIBA",9],
		["YAJILON",3],
		["DODEKABASHI",7],
		["KAPU-BULUL",7],
		["FREEGEO",5],
		["KICHIKIGISU",9],
		["YAYAKOMA",6],
		["BUBY",2],
		["REGISTEEL",3],
		["NAKANUCHAN",9],
		["GRAENA",3],
		["YOWASHI",7],
		["HOSHIGARISU",8],
		["NAMIIRUKA",9],
		["KAMITURUGI",7],
		["COBALON",5],
		["WANAIDER",9],
		["MONMEN",5],
		["ROUBUSHIN",5],
		["EIEVUI",1],
		["KAMEX",1],
		["SUNABA",7],
		["UMIDIGDA",9],
		["DOSIDON",4],
		["MIGALUSA",9],
		["SKUTANK",4],
		["WANINOKO",2],
		["EXLEG",9],
		["MEECLE",6],
		["MIMIROL",4],
		["DODAITOSE",4],
		["ZUGAIDOS",4],
		["BOOPIG",3],
		["CROBAT",2],
		["KAMUKAME",8],
		["CRAB",1],
		["KYOJIOHN",9],
		["HINOYAKOMA",6],
		["GALLOP",1],
		["ANOKUSA",9],
		["GAKEGANI",9],
		["DOUBLAN",5],
		["NIDORINA",1],
		["VULGINA",5],
		["BUOYSEL",4],
		["HIMENKA",8],
		["ELEKIBLE",4],
		["PATCHEEL",3],
		["HAGANEIL",2],
		["NYAROTE",9],
		["BAIWOOLUU",8],
		["GOLBAT",1],
		["KAIRIKY",1],
		["ZURUZUKIN",5],
		["TAMAZARASHI",3],
		["KUNUGIDAMA",2],
		["BRIMUON",8],
		["MARIL",2],
		["OTOSHIDORI",9],
		["FUSHIGIBANA",1],
		["KOSOKUMUSHI",7],
		["MINUN",3],
		["KUCHEAT",3],
		["BEVENOM",7],
		["NUMACRAW",3],
		["SYMBOLER",5],
		["MESSON",8],
		["HORUBEE",6],
		["UONORAGON",8],
		["KERARAPPA",7],
		["PARASECT",1],
		["REGIGIGAS",4],
		["SUBOMIE",4],
		["ARBO",1],
		["KOARUHIE",5],
		["ASHIRENE",7],
		["TOGEKISS",4],
		["OLINYO",9],
		["CAMOME",3],
		["CUWAWA",7],
		["PORYGON2",2],
		["NYULA",2],
		["LANTERN",2],
		["MIKARUGE",4],
		["FLYGON",3],
		["URIMOO",2],
		["PULSEWAN",8],
		["JUPTILE",3],
		["KOKOGARA",8],
		["LAMPLER",5],
		["IDAITOU",8],
		["PARMOT",9],
		["IRUKAMAN",9],
		["KONOHANA",3],
		["ZUGADOON",7],
		["MILOKAROSS",3],
		["ENBUOH",5],
		["MELTAN",7],
		["KORIPPO",8],
		["KIRAFLOR",9],
		["HERACROS",2],
		["MUMA",2],
		["COLLECUREI",9],
		["CHORONEKO",5],
		["ABURIBBON",7],
		["INTEREON",8],
		["TABUNNE",5],
		["BOKUREI",6],
		["BURUNGEL",5],
		["BURORON",9],
		["KAJIRIGAME",8],
		["OKORIZARU",1],
		["MIJUMARU",5],
		["LOVETOLOS",8],
		["YORTERRIE",5],
		["ELFUUN",5],
		["BEROBELT",4],
		["UMITRIO",9],
		["HITOKAGE",1],
		["CREBASE",6],
		["KIRIKIZAN",5],
		["PEROPPAFU",6],
		["TAKERURAIKO",9],
		["MENOKURAGE",1],
		["LANDLOS",5],
		["BUDREX",8],
		["KAJICCHU",8],
		["KARASALIS",3],
		["MOTHNOW",8],
		["GAMALE",4],
		["HIHIDARUMA",5],
		["KIREIHANA",2],
		["YANYANMA",2],
		["MOKUROH",7],
		["SEBIE",9],
		["RABBIFUTO",8],
		["KUWASSU",9],
		["TOROGGON",8],
		["ELEKID",2],
		["KARAKARA",1],
		["MAMEPATO",5],
		["REDIAN",2],
		["DANGORO",5],
		["ERUREIDO",4],
		["LALANTES",7],
		["DORAMESHIYA",8],
		["POCHIENA",3],
		["MAGCARGOT",2],
		["OOTACHI",2],
		["MASHIMASHIRA",9],
		["OKUTANK",2],
		["WANIVAL",9],
		["KIRAME",9],
		["BARRIKOHRU",8],
		["GIARU",5],
		["HAKADOG",9],
		["SEKITANZAN",8],
		["CHURINE",5],
		["GARURA",1],
		["NYAIKING",8],
		["IKIRINKO",9],
		["BRIDURAS",9],
		["DOOH",9],
		["KABIGON",1],
		["SLEEPER",1],
		["UGATSUHOMURA",9],
		["BAKECCHA",6],
		["MIRAIDON",9],
		["ANOPTH",3],
		["SHUSHUPU",6],
		["FOODIN",1],
		["GOLONE",1],
		["HITOTSUKI",6],
		["DOGOHMB",3],
		["SHAYMIN",4],
		["VALCHAI",5],
		["PURIN",1],
		["DIRTENG",3],
		["BIRIRIDAMA",1],
		["JIGUZAGUMA",3],
		["NYOROBON",1],
		["CHIGORAS",6],
		["CASEY",1],
		["NUMEIL",6],
		["DREDEAR",5],
		["TRITODON",4],
		["KIMORI",3],
		["SOLGALEO",7],
		["MAGEARNA",7],
		["KOROMORI",5],
		["EMPERTE",4],
		["ZACIAN",8],
		["PUMPJIN",6],
		["DAGEKI",5],
		["IKKANEZUMI",9],
		["NOCTUS",3],
		["KENHALLOW",5],
		["TODOGGLER",3],
		["SIHORN",1],
		["KUWAGANNON",7],
		["ZARUDE",8],
		["NIDANGILL",6],
		["JALORDA",5],
		["CATERPIE",1],
		["GEKOGASHIRA",6],
		["WANRIKY",1],
		["MERLARVA",5],
		["TORIDEPS",4],
		["METAMON",1],
		["YUKIMENOKO",4],
		["AMEMOTH",3],
		["TETSUNOKOUBE",9],
		["KODUCK",1],
		["YADORAN",1],
		["NYARMAR",4],
		["OHLONGE",8],
		["CHAREM",3],
		["NAGETUKESARU",7],
		["DIANCIE",6],
		["TETSUNOIBARA",9],
		["PIGEOT",1],
		["SKUNPUU",4],
		["DORAPION",4],
		["BAYLEAF",2],
		["BAKUONG",3],
		["BACHINUNI",8],
		["CHOBOMAKI",5],
		["PEROREAM",6],
		["KOIKING",1],
		["LUNATONE",3],
		["KIMAWARI",2],
		["SACCHIMUSHI",8],
		["PICHU",2],
		["TAIRENAR",6],
		["WARUVILE",5],
		["FLOAZEL",4],
		["ZUPIKA",9],
		["CHEVARGO",5],
		["MARILLI",2],
		["ACHAMO",3],
		["KOMORUU",3],
		["NECROZMA",7],
		["SANDPAN",1],
		["CHERRIM",4],
		["EBIWALAR",1],
		["ZEBRAIKA",5],
		["MONJARA",1],
		["REDIBA",2],
		["GEKKOUGA",6],
		["MANENE",4],
		["WASHIBON",5],
		["FOXLY",8],
		["DENDIMUSHI",7],
		["GENESECT",5],
		["PARSHEN",1],
		["CHONCHIE",2],
		["TODOSERUGA",3],
		["YANAPPU",5],
		["COIL",1],
		["GLANTH",3],
		["STARMIE",1],
		["GLIGER",2],
		["IWARK",1],
		["KABALDON",4],
		["BACHURU",5],
		["COSMOVUM",7],
		["DORYUZU",5],
		["NYABBY",7],
		["JUPPETA",3],
		["JUKAIN",3],
		["CHILLARMY",5],
		["MEWTWO",1],
		["HASSAM",2],
		["JYARANGO",7],
		["ARABURUTAKE",9],
		["FUSHIGIDANE",1],
		["NIDORAN♂",1],
		["GIGAIATH",5],
		["YADOKING",2],
		["SIDON",1],
		["DODORIO",1],
		["TOGEDEMARU",7],
		["HIRAHINA",9],
		["LEPARDAS",5],
		["OLIVA",9],
		["MAAIIKA",6],
		["YORUNOZUKU",2],
		["SAMEHADER",3],
		["ISITSUBUTE",1],
		["WARUVIAL",5],
		["FREEZER",1],
		["YAKUDE",8],
		["KOJOFU",5],
		["ASANAN",3],
		["GONBE",4],
		["KACHIKOHRU",6],
		["BLOSTER",6],
		["POCHAMA",4],
		["OHBEM",5],
		["ONIDRILL",1],
		["MORPEKO",8],
		["BRIGARRON",6],
		["KAMASUJAW",8],
		["HOERUKO",3],
		["EIPAM",2],
		["HIYAPPU",5],
		["MUKUBIRD",4],
		["HOGATOR",9],
		["KYUKON",1],
		["KORATTA",1],
		["UTUROID",7],
		["TESSEED",5],
		["ARIADOS",2],
		["MAFITIFF",9],
		["KINOGASSA",3],
		["SONANS",2],
		["LIZARDON",1],
		["DEDENNE",6],
		["SWANNA",5],
		["AGOYON",7],
		["KUMASYUN",5],
		["TOGECHICK",2],
		["DIGDA",1],
		["HAGIGISHIRI",7],
		["VIVIYON",6],
		["LUCKY",1],
		["AZUMAO",1],
		["PUPURIN",2],
		["MELMETAL",7],
		["PINPUKU",4],
		["HITODEMAN",1],
		["RESHIRAM",5],
		["NEKKOARA",7],
		["NOSEPASS",3],
		["MOGUREW",5],
		["MUKUHAWK",4],
		["SASIKAMASU",8],
		["KYOGRE",3],
		["OMNITE",1],
		["BOOBER",1],
		["NIDORAN♀",1],
		["MINIVE",9],
		["YOUNGOOSE",7],
		["WANPACHI",8],
		["GACHIGORAS",6],
		["HAYASHIGAME",4],
		["SURFUGO",9],
		["NUTREY",5],
		["OTAMARO",5],
		["POPOCCO",2],
		["KABURUMO",5],
		["GACHIGUMA",8],
		["METENO",7],
		["PACHIRISU",4],
		["JANOVY",5],
		["NYMPHIA",6],
		["CRIMGAN",5],
		["HARITEYAMA",3],
		["LUCHABULL",6],
		["TEBRIM",8],
		["HASUBRERO",3],
		["SAZANDORA",5],
		["KOROTOCK",4],
		["REGIROCK",3],
		["MEBUKIJIKA",5],
		["KITERUGUMA",7],
		["RAICHU",1],
		["BRACKY",2],
		["ROKON",1],
		["DENJYUMOKU",7],
		["SILVADY",7],
		["HEYRUSHER",9],
		["KYUREM",5],
		["ODORIDORI",7],
		["LANCULUS",5],
		["PAWOU",1],
		["BEEDLE",1],
		["PALKIA",4],
		["MARUMINE",1],
		["NYOROTONO",2],
		["KAMONEGI",1],
		["ROTOM",4],
		["TOSAKINTO",1],
		["DINLU",9],
		["KUSUNE",8],
		["SHIRUSHREW",9],
		["GIMOH",8],
		["NIDORINO",1],
		["DELIBIRD",2],
		["COSMOG",7],
		["BOWTZEL",9],
		["BAKUGAMES",7],
		/*["PY",2],
		["UU",8],
		["MEW",1],
		["TETSUNODOKUGA",9],
		["TODOROKUTSUKI",9],
		["KAMITSUOROCHI",9],
		["TACHIFUSAGUMA",8],
		["TETSUNOWADACHI",9],
		["TETSUNOKASHIRA",9],
		["TETSUNOTSUTSUMI",9],*/
	] as [string, number][]);
	
	public static readonly PropositionsUniquement: Map<string, number> = new Map<string, number>([
		["MANGUSPEKTOR",7],
		["EISENBUENDEL",9],
		["DONNERSICHEL",9],
		["EISENKRIEGER",9],
	] as [string, number][]);
}
